import XCTest
@testable import DevIsland

/// Golden parity test for the String Catalog migration.
///
/// Verifies every L10n facade property/func resolves through the compiled
/// `Localizable.xcstrings` to exactly the pre-migration en/ko text, in both
/// languages, including format specifiers (%@, %lld, positional, %%). Originally
/// emitted by `scripts/gen_l10n.py`; extend by hand when adding strings.
final class LocalizableCatalogGoldenTests: XCTestCase {
    private let l10n = L10n.shared

    override func tearDown() {
        l10n.language = .system
        super.tearDown()
    }

    func testEnglishCatalogMatchesLegacy() {
        l10n.language = .english
        XCTAssertEqual(l10n.menuNoPending, "No pending requests", "menuNoPending")
        XCTAssertEqual(l10n.menuPending, "Requests pending", "menuPending")
        XCTAssertEqual(l10n.menuFocusTerminal, "Focus Terminal", "menuFocusTerminal")
        XCTAssertEqual(l10n.menuApprove, "Approve  ⌘⇧Y", "menuApprove")
        XCTAssertEqual(l10n.menuDeny, "Deny  ⌘⇧N", "menuDeny")
        XCTAssertEqual(l10n.menuSettings, "Settings…", "menuSettings")
        XCTAssertEqual(l10n.menuApprovalRules, "Approval Rules…", "menuApprovalRules")
        XCTAssertEqual(l10n.menuReplayLog, "Replay Log…", "menuReplayLog")
        XCTAssertEqual(l10n.menuPTYTranscript, "PTY Transcript…", "menuPTYTranscript")
        XCTAssertEqual(l10n.menuSessionHistory, "Session History…", "menuSessionHistory")
        XCTAssertEqual(l10n.menuInstallHooks, "Install / Repair Hooks", "menuInstallHooks")
        XCTAssertEqual(l10n.menuInstallAll, "Install All (Claude · Codex · Gemini · Antigravity)", "menuInstallAll")
        XCTAssertEqual(l10n.menuInstallClaude, "Install Claude Code only…", "menuInstallClaude")
        XCTAssertEqual(l10n.menuInstallCodex, "Install Codex CLI only…", "menuInstallCodex")
        XCTAssertEqual(l10n.menuInstallGemini, "Install Gemini CLI only…", "menuInstallGemini")
        XCTAssertEqual(l10n.menuInstallAntigravity, "Install Antigravity CLI only…", "menuInstallAntigravity")
        XCTAssertEqual(l10n.menuRemoveAll, "Remove All (Claude · Codex · Gemini · Antigravity)", "menuRemoveAll")
        XCTAssertEqual(l10n.menuRemoveClaude, "Remove Claude Code only…", "menuRemoveClaude")
        XCTAssertEqual(l10n.menuRemoveCodex, "Remove Codex CLI only…", "menuRemoveCodex")
        XCTAssertEqual(l10n.menuRemoveGemini, "Remove Gemini CLI only…", "menuRemoveGemini")
        XCTAssertEqual(l10n.menuRemoveAntigravity, "Remove Antigravity CLI only…", "menuRemoveAntigravity")
        XCTAssertEqual(l10n.menuAccessibility, "Request Accessibility Permission…", "menuAccessibility")
        XCTAssertEqual(l10n.menuCheckForUpdates, "Check for Updates…", "menuCheckForUpdates")
        XCTAssertEqual(l10n.menuUpdateAvailable("v"), "Update Available (v)…", "menuUpdateAvailable")
        XCTAssertEqual(l10n.menuQuit, "Quit DevIsland", "menuQuit")
        XCTAssertEqual(l10n.alertAllInstalled, "All Hooks Installed", "alertAllInstalled")
        XCTAssertEqual(l10n.alertClaudeInstalled, "Claude Code Installed", "alertClaudeInstalled")
        XCTAssertEqual(l10n.alertClaudeInstallFailed, "Claude Code Installation Failed", "alertClaudeInstallFailed")
        XCTAssertEqual(l10n.alertCodexInstalled, "Codex CLI Installed", "alertCodexInstalled")
        XCTAssertEqual(l10n.alertCodexInstallFailed, "Codex CLI Installation Failed", "alertCodexInstallFailed")
        XCTAssertEqual(l10n.alertGeminiInstalled, "Gemini CLI Installed", "alertGeminiInstalled")
        XCTAssertEqual(l10n.alertGeminiInstallFailed, "Gemini CLI Installation Failed", "alertGeminiInstallFailed")
        XCTAssertEqual(l10n.alertAntigravityInstalled, "Antigravity CLI Installed", "alertAntigravityInstalled")
        XCTAssertEqual(l10n.alertAntigravityInstallFailed, "Antigravity CLI Installation Failed", "alertAntigravityInstallFailed")
        XCTAssertEqual(l10n.alertInstallFailed, "Installation Failed", "alertInstallFailed")
        XCTAssertEqual(l10n.alertAllInstalledMsg, "All bridge hooks installed.\nRestart each CLI session.", "alertAllInstalledMsg")
        XCTAssertEqual(l10n.alertBridgeInstalled, "Bridge installed.\nRestart your session.", "alertBridgeInstalled")
        XCTAssertEqual(l10n.alertClaudeRestartMsg, "Bridge installed.\nRestart your Claude Code session.", "alertClaudeRestartMsg")
        XCTAssertEqual(l10n.alertCodexRestartMsg, "Bridge installed.\nRestart your Codex CLI session.", "alertCodexRestartMsg")
        XCTAssertEqual(l10n.alertGeminiRestartMsg, "Bridge installed.\nRestart your Gemini CLI session.", "alertGeminiRestartMsg")
        XCTAssertEqual(l10n.alertAntigravityRestartMsg, "Bridge installed.\nRestart your Antigravity CLI session.", "alertAntigravityRestartMsg")
        XCTAssertEqual(l10n.alertBundleNoScript, "Bridge script not found in app bundle.", "alertBundleNoScript")
        XCTAssertEqual(l10n.alertBundleNoHelper, "Bridge helper not found in app bundle.", "alertBundleNoHelper")
        XCTAssertEqual(l10n.alertBundleNoManifest, "Hook event manifest not found in app bundle.", "alertBundleNoManifest")
        XCTAssertEqual(l10n.alertBundleNoInstaller, "Hook installer script not found in app bundle.", "alertBundleNoInstaller")
        XCTAssertEqual(l10n.alertBundleNoCodexWrapper, "Codex Auto-review wrapper not found in app bundle.", "alertBundleNoCodexWrapper")
        XCTAssertEqual(l10n.alertInstallScriptFailed("detail"), "Hook installer failed: detail", "alertInstallScriptFailed")
        XCTAssertEqual(l10n.alertBadJSON, "Failed to parse settings.json: invalid JSON format.", "alertBadJSON")
        XCTAssertEqual(l10n.alertBadFile("name"), "Failed to parse name", "alertBadFile")
        XCTAssertEqual(l10n.alertAllRemoved, "All Removed", "alertAllRemoved")
        XCTAssertEqual(l10n.alertAllRemovedMsg, "All bridge hooks removed.\nRestart each CLI session.", "alertAllRemovedMsg")
        XCTAssertEqual(l10n.alertSomeRemoveFailed, "Some Removals Failed", "alertSomeRemoveFailed")
        XCTAssertEqual(l10n.alertClaudeRemoved, "Claude Code Removed", "alertClaudeRemoved")
        XCTAssertEqual(l10n.alertClaudeRemoveFailed, "Claude Code Removal Failed", "alertClaudeRemoveFailed")
        XCTAssertEqual(l10n.alertCodexRemoved, "Codex CLI Removed", "alertCodexRemoved")
        XCTAssertEqual(l10n.alertCodexRemoveFailed, "Codex CLI Removal Failed", "alertCodexRemoveFailed")
        XCTAssertEqual(l10n.alertGeminiRemoved, "Gemini CLI Removed", "alertGeminiRemoved")
        XCTAssertEqual(l10n.alertGeminiRemoveFailed, "Gemini CLI Removal Failed", "alertGeminiRemoveFailed")
        XCTAssertEqual(l10n.alertAntigravityRemoved, "Antigravity CLI Removed", "alertAntigravityRemoved")
        XCTAssertEqual(l10n.alertAntigravityRemoveFailed, "Antigravity CLI Removal Failed", "alertAntigravityRemoveFailed")
        XCTAssertEqual(l10n.alertHooksRemoved, "Hooks removed.\nRestart your session.", "alertHooksRemoved")
        XCTAssertEqual(l10n.alertClaudeHooksRemoved, "Hooks removed.\nRestart your Claude Code session.", "alertClaudeHooksRemoved")
        XCTAssertEqual(l10n.alertCodexHooksRemoved, "Hooks removed.\nRestart your Codex CLI session.", "alertCodexHooksRemoved")
        XCTAssertEqual(l10n.alertGeminiHooksRemoved, "Hooks removed.\nRestart your Gemini CLI session.", "alertGeminiHooksRemoved")
        XCTAssertEqual(l10n.alertAntigravityHooksRemoved, "Hooks removed.\nRestart your Antigravity CLI session.", "alertAntigravityHooksRemoved")
        XCTAssertEqual(l10n.alertOK, "OK", "alertOK")
        XCTAssertEqual(l10n.relocateTitle, "Move to Applications Folder?", "relocateTitle")
        XCTAssertEqual(l10n.relocateMessage, "Move DevIsland to the Applications folder to continue using it.", "relocateMessage")
        XCTAssertEqual(l10n.relocateMoveBtn, "Move and Relaunch", "relocateMoveBtn")
        XCTAssertEqual(l10n.relocateLaterBtn, "Later", "relocateLaterBtn")
        XCTAssertEqual(l10n.relocateFailTitle, "Move Failed", "relocateFailTitle")
        XCTAssertEqual(l10n.relocateNoPermMsg, "No write permission for the Applications folder. Please move manually using Finder.", "relocateNoPermMsg")
        XCTAssertEqual(l10n.relocateErrMsg("err"), "An error occurred while moving the app: err", "relocateErrMsg")
        XCTAssertEqual(l10n.dmgCleanTitle, "Clean Up Installer?", "dmgCleanTitle")
        XCTAssertEqual(l10n.dmgCleanMessage, "Installation is complete. Would you like to eject and clean up the installer (DMG)?", "dmgCleanMessage")
        XCTAssertEqual(l10n.dmgCleanBtn, "Clean Up", "dmgCleanBtn")
        XCTAssertEqual(l10n.dmgNoBtn, "No", "dmgNoBtn")
        XCTAssertEqual(l10n.dmgEjectFailTitle, "Eject Failed", "dmgEjectFailTitle")
        XCTAssertEqual(l10n.dmgEjectFailMsg, "Failed to eject the installer. Please eject manually from Finder.", "dmgEjectFailMsg")
        XCTAssertEqual(l10n.updateAvailableTitle, "Update Available", "updateAvailableTitle")
        XCTAssertEqual(l10n.updateChangeLogTitle, "Release Notes / Change Log", "updateChangeLogTitle")
        XCTAssertEqual(l10n.updateAvailableMsg("v"), "DevIsland v is available.\nInstall and relaunch?", "updateAvailableMsg")
        XCTAssertEqual(l10n.updateInstallBtn, "Install and Relaunch", "updateInstallBtn")
        XCTAssertEqual(l10n.updateLaterBtn, "Later", "updateLaterBtn")
        XCTAssertEqual(l10n.updateUpToDateTitle, "Up to Date", "updateUpToDateTitle")
        XCTAssertEqual(l10n.updateUpToDateMsg("v"), "DevIsland v is the latest version.", "updateUpToDateMsg")
        XCTAssertEqual(l10n.updateDownloading, "Downloading…", "updateDownloading")
        XCTAssertEqual(l10n.updateInstalling, "Installing…", "updateInstalling")
        XCTAssertEqual(l10n.updateRelaunching, "Relaunching…", "updateRelaunching")
        XCTAssertEqual(l10n.updateFailedTitle, "Update Failed", "updateFailedTitle")
        XCTAssertEqual(l10n.updateCheckFailedTitle, "Update Check Failed", "updateCheckFailedTitle")
        XCTAssertEqual(l10n.updateInvalidResponseMsg, "Invalid response from GitHub.", "updateInvalidResponseMsg")
        XCTAssertEqual(l10n.updateNoAssetMsg, "No DMG found in the latest release.", "updateNoAssetMsg")
        XCTAssertEqual(l10n.winSettings, "DevIsland Settings", "winSettings")
        XCTAssertEqual(l10n.winApprovalRules, "Approval Rules", "winApprovalRules")
        XCTAssertEqual(l10n.winReplayLog, "Replay Log", "winReplayLog")
        XCTAssertEqual(l10n.winPTYTranscript, "PTY Transcript", "winPTYTranscript")
        XCTAssertEqual(l10n.winSessionHistory, "Session History", "winSessionHistory")
        XCTAssertEqual(l10n.tabGeneral, "General", "tabGeneral")
        XCTAssertEqual(l10n.tabIsland, "Island", "tabIsland")
        XCTAssertEqual(l10n.tabApproval, "Approval", "tabApproval")
        XCTAssertEqual(l10n.tabProviders, "Providers", "tabProviders")
        XCTAssertEqual(l10n.tabBridge, "Bridge / IPC", "tabBridge")
        XCTAssertEqual(l10n.tabExperimental, "Experimental", "tabExperimental")
        XCTAssertEqual(l10n.tabDiagnostics, "Diagnostics", "tabDiagnostics")
        XCTAssertEqual(l10n.tabIntegrations, "Integrations", "tabIntegrations")
        XCTAssertEqual(l10n.tabExtras, "Extras", "tabExtras")
        XCTAssertEqual(l10n.tabAdvanced, "Advanced", "tabAdvanced")
        XCTAssertEqual(l10n.tabPlugins, "Plugins", "tabPlugins")
        XCTAssertEqual(l10n.secBridgeScript, "Bridge Script", "secBridgeScript")
        XCTAssertEqual(l10n.lblBridgeInstallPath, "Install path", "lblBridgeInstallPath")
        XCTAssertEqual(l10n.lblBridgeFileFound, "Installed", "lblBridgeFileFound")
        XCTAssertEqual(l10n.lblBridgeFileNotFound, "Not found", "lblBridgeFileNotFound")
        XCTAssertEqual(l10n.secHookStatus, "Hook install status", "secHookStatus")
        XCTAssertEqual(l10n.lblHookInstalled, "Installed", "lblHookInstalled")
        XCTAssertEqual(l10n.lblHookNotInstalled, "Not installed", "lblHookNotInstalled")
        XCTAssertEqual(l10n.lblHookFileMissing, "File missing", "lblHookFileMissing")
        XCTAssertEqual(l10n.secLastEvent, "Last event received", "secLastEvent")
        XCTAssertEqual(l10n.lblNoEventYet, "None", "lblNoEventYet")
        XCTAssertEqual(l10n.secBridgeLog, "Bridge log (last 20 lines)", "secBridgeLog")
        XCTAssertEqual(l10n.secBridgeLogEmpty, "Log file not found", "secBridgeLogEmpty")
        XCTAssertEqual(l10n.btnDiagRefresh, "Refresh", "btnDiagRefresh")
        XCTAssertEqual(l10n.pluginsEmpty, "No plugins registered.", "pluginsEmpty")
        XCTAssertEqual(l10n.pluginsListHeader, "Built-in Plugins", "pluginsListHeader")
        XCTAssertEqual(l10n.lblPluginSafemode, "Safe mode — disabled after repeated errors", "lblPluginSafemode")
        XCTAssertEqual(l10n.btnPluginReset, "Reset", "btnPluginReset")
        XCTAssertEqual(l10n.btnPluginResetStorage, "Reset Storage", "btnPluginResetStorage")
        XCTAssertEqual(l10n.msgPluginResetStorageConfirm, "Are you sure you want to delete all stored data for this plugin? This cannot be undone.", "msgPluginResetStorageConfirm")
        XCTAssertEqual(l10n.pluginFailures(7), "Errors: 7", "pluginFailures")
        XCTAssertEqual(l10n.lblPluginSettings, "Settings", "lblPluginSettings")
        XCTAssertEqual(l10n.secCaffeineStatus, "Status", "secCaffeineStatus")
        XCTAssertEqual(l10n.secCaffeineBehavior, "Behavior", "secCaffeineBehavior")
        XCTAssertEqual(l10n.secCaffeineExcludedSSIDs, "Excluded Wi-Fi Networks", "secCaffeineExcludedSSIDs")
        XCTAssertEqual(l10n.lblCaffeineEnabled, "Enable Caffeine", "lblCaffeineEnabled")
        XCTAssertEqual(l10n.lblCurrentSSID, "Current Wi-Fi", "lblCurrentSSID")
        XCTAssertEqual(l10n.lblOnAC, "On AC Power", "lblOnAC")
        XCTAssertEqual(l10n.lblBatteryLevel, "Battery", "lblBatteryLevel")
        XCTAssertEqual(l10n.lblHoldingAssertion, "Preventing sleep", "lblHoldingAssertion")
        XCTAssertEqual(l10n.btnAddSSID, "Add SSID…", "btnAddSSID")
        XCTAssertEqual(l10n.lblScanNearbyWifi, "Nearby Wi-Fi", "lblScanNearbyWifi")
        XCTAssertEqual(l10n.lblConnectedSSID, "Connected", "lblConnectedSSID")
        XCTAssertEqual(l10n.lblManualSSIDEntry, "Enter SSID manually", "lblManualSSIDEntry")
        XCTAssertEqual(l10n.lblScanFailed, "Scan failed (Location permission required)", "lblScanFailed")
        XCTAssertEqual(l10n.lblScanErrorPermission, "Location permission required to scan Wi-Fi", "lblScanErrorPermission")
        XCTAssertEqual(l10n.lblScanErrorRadioOff, "Wi-Fi is turned off", "lblScanErrorRadioOff")
        XCTAssertEqual(l10n.lblScanErrorUnknown("detail"), "Scan failed: detail", "lblScanErrorUnknown")
        XCTAssertEqual(l10n.btnOpenLocationSettings, "Open System Settings", "btnOpenLocationSettings")
        XCTAssertEqual(l10n.hintCaffeineRule, "When enabled, sleep is prevented while on AC power; always off on excluded Wi-Fi or when battery is ≤ 20%.", "hintCaffeineRule")
        XCTAssertEqual(l10n.secCaffeineSessionTimeout, "Session Idle Timeout", "secCaffeineSessionTimeout")
        XCTAssertEqual(l10n.lblCaffeineSessionTimeoutEnabled, "Deactivate when sessions are idle", "lblCaffeineSessionTimeoutEnabled")
        XCTAssertEqual(l10n.lblCaffeineSessionTimeoutMinutes(7), "Timeout: 7 min", "lblCaffeineSessionTimeoutMinutes")
        XCTAssertEqual(l10n.hintCaffeineSessionTimeout, "Caffeine turns off automatically after all sessions have been idle or terminated for the configured duration.", "hintCaffeineSessionTimeout")
        XCTAssertEqual(l10n.menuCaffeineToggle, "Caffeine", "menuCaffeineToggle")
        XCTAssertEqual(l10n.menuCaffeineOnAC, "Preventing sleep — AC power", "menuCaffeineOnAC")
        XCTAssertEqual(l10n.menuCaffeineOff, "Off", "menuCaffeineOff")
        XCTAssertEqual(l10n.menuCaffeineOnBattery, "Off — on battery", "menuCaffeineOnBattery")
        XCTAssertEqual(l10n.menuCaffeineLowBattery, "Off — low battery", "menuCaffeineLowBattery")
        XCTAssertEqual(l10n.menuCaffeineExcludedSSID("ssid"), "Off — excluded Wi-Fi (ssid)", "menuCaffeineExcludedSSID")
        XCTAssertEqual(l10n.menuCaffeineFailure(7), "Failed to acquire sleep assertion (code 7)", "menuCaffeineFailure")
        XCTAssertEqual(l10n.secAppIntegrations, "App Integrations", "secAppIntegrations")
        XCTAssertEqual(l10n.lblProcessVSCode, "Enable VS Code integration", "lblProcessVSCode")
        XCTAssertEqual(l10n.descProcessVSCode, "Process hook events from sessions running in VS Code.", "descProcessVSCode")
        XCTAssertEqual(l10n.lblProcessClaudeDesktop, "Enable Claude Desktop integration", "lblProcessClaudeDesktop")
        XCTAssertEqual(l10n.descProcessClaudeDesktop, "Process hook events from sessions running in Claude Desktop.", "descProcessClaudeDesktop")
        XCTAssertEqual(l10n.lblProcessCodexDesktop, "Enable Codex Desktop integration", "lblProcessCodexDesktop")
        XCTAssertEqual(l10n.descProcessCodexDesktop, "Process hook events from sessions running in Codex Desktop.", "descProcessCodexDesktop")
        XCTAssertEqual(l10n.btnResetAllSettings, "Reset All Settings to Defaults", "btnResetAllSettings")
        XCTAssertEqual(l10n.secLanguage, "Language", "secLanguage")
        XCTAssertEqual(l10n.lblLanguage, "Language", "lblLanguage")
        XCTAssertEqual(l10n.secPreferredTerminal, "Default Terminal", "secPreferredTerminal")
        XCTAssertEqual(l10n.lblPreferredTerminal, "Open sessions in", "lblPreferredTerminal")
        XCTAssertEqual(l10n.optTerminalSessionDefault, "Session's terminal (automatic)", "optTerminalSessionDefault")
        XCTAssertEqual(l10n.hintPreferredTerminal, "Used when opening a session in a new terminal window. Falls back to the session's original terminal app if not set.", "hintPreferredTerminal")
        XCTAssertEqual(l10n.secAoEFocus, "AoE Session Focus", "secAoEFocus")
        XCTAssertEqual(l10n.lblAoEFocusMode, "Focus mode", "lblAoEFocusMode")
        XCTAssertEqual(l10n.hintAoEFocusMode, "The safer tmux mode avoids sending /session text into AoE. Use manager search only if you want dashboard row navigation.", "hintAoEFocusMode")
        XCTAssertEqual(l10n.aoeFocusTmuxClient, "tmux client switch", "aoeFocusTmuxClient")
        XCTAssertEqual(l10n.aoeFocusManagerSearch, "AoE dashboard search", "aoeFocusManagerSearch")
        XCTAssertEqual(l10n.detailAoEFocusTmuxClient, "Focus the terminal and switch the tmux client/pane without typing into AoE.", "detailAoEFocusTmuxClient")
        XCTAssertEqual(l10n.detailAoEFocusManagerSearch, "Send Ctrl+Q, /, the session title, and Enter to the AoE dashboard after focusing.", "detailAoEFocusManagerSearch")
        XCTAssertEqual(l10n.secStartup, "Startup", "secStartup")
        XCTAssertEqual(l10n.lblLaunchAtLogin, "Launch at Login", "lblLaunchAtLogin")
        XCTAssertEqual(l10n.lblLaunchAtLoginApproval, "Approval required in System Settings", "lblLaunchAtLoginApproval")
        XCTAssertEqual(l10n.btnOpenLoginSettings, "Open Login Items Settings…", "btnOpenLoginSettings")
        XCTAssertEqual(l10n.alertLaunchAtLoginFailed, "Failed to change Launch at Login", "alertLaunchAtLoginFailed")
        XCTAssertEqual(l10n.secUpdates, "Updates", "secUpdates")
        XCTAssertEqual(l10n.lblCheckForUpdatesOnStartup, "Check for updates on startup", "lblCheckForUpdatesOnStartup")
        XCTAssertEqual(l10n.lblReleaseChannel, "Update channel", "lblReleaseChannel")
        XCTAssertEqual(l10n.releaseChannelStable, "Stable", "releaseChannelStable")
        XCTAssertEqual(l10n.releaseChannelNightly, "Nightly", "releaseChannelNightly")
        XCTAssertEqual(l10n.secSounds, "Sounds", "secSounds")
        XCTAssertEqual(l10n.lblMuteAllSounds, "Mute all sounds", "lblMuteAllSounds")
        XCTAssertEqual(l10n.secNotifications, "Notifications", "secNotifications")
        XCTAssertEqual(l10n.lblNotificationsEnabled, "Notify me on approval requests", "lblNotificationsEnabled")
        XCTAssertEqual(l10n.descNotificationsEnabled, "Sends a macOS notification when a tool needs approval. Includes Approve and Deny buttons when app is in background.", "descNotificationsEnabled")
        XCTAssertEqual(l10n.notifActionApprove, "Allow", "notifActionApprove")
        XCTAssertEqual(l10n.notifActionDeny, "Deny", "notifActionDeny")
        XCTAssertEqual(l10n.notifApprovalBody, "Approval required.", "notifApprovalBody")
        XCTAssertEqual(l10n.notifTaskCompleteTitle, "Task complete", "notifTaskCompleteTitle")
        XCTAssertEqual(l10n.secNotch, "Island", "secNotch")
        XCTAssertEqual(l10n.lblDisplay, "Display", "lblDisplay")
        XCTAssertEqual(l10n.lblMonitor, "Monitor", "lblMonitor")
        XCTAssertEqual(l10n.lblShowFullScreen, "Show above full-screen apps", "lblShowFullScreen")
        XCTAssertEqual(l10n.lblPanelOpacity(7), "Panel opacity: 7%", "lblPanelOpacity")
        XCTAssertEqual(l10n.lblNotchShadow, "Backdrop shadow", "lblNotchShadow")
        XCTAssertEqual(l10n.lblNotchAnimation, "Expand/collapse animation", "lblNotchAnimation")
        XCTAssertEqual(l10n.lblAnimationSpeed(1.25), "Animation speed: 1.25×", "lblAnimationSpeed")
        XCTAssertEqual(l10n.lblNotchShapeStyle, "Shape style", "lblNotchShapeStyle")
        XCTAssertEqual(l10n.notchShapeClassic, "Classic Island", "notchShapeClassic")
        XCTAssertEqual(l10n.notchShapeDynamicIsland, "Dynamic Island", "notchShapeDynamicIsland")
        XCTAssertEqual(l10n.lblCollapsedNotchWidth(7), "Compact Island width: 7 px", "lblCollapsedNotchWidth")
        XCTAssertEqual(l10n.lblCollapsedNotchHeight(7), "Compact Island height: 7 px", "lblCollapsedNotchHeight")
        XCTAssertEqual(l10n.lblExpandedNotchWidth(7), "Expanded Island width: 7 px", "lblExpandedNotchWidth")
        XCTAssertEqual(l10n.lblExpandedNotchHeight(7), "Expanded Island height: 7 px", "lblExpandedNotchHeight")
        XCTAssertEqual(l10n.lblNotchAutoExpand, "Auto-expand on events", "lblNotchAutoExpand")
        XCTAssertEqual(l10n.lblUnreadDotPosition, "Unread dot position", "lblUnreadDotPosition")
        XCTAssertEqual(l10n.posLeft, "Left", "posLeft")
        XCTAssertEqual(l10n.posCenter, "Center", "posCenter")
        XCTAssertEqual(l10n.posRight, "Right", "posRight")
        XCTAssertEqual(l10n.lblNotchAutoCollapse, "Auto-collapse", "lblNotchAutoCollapse")
        XCTAssertEqual(l10n.secNotchAutoExpand, "Auto-expand", "secNotchAutoExpand")
        XCTAssertEqual(l10n.secNotchExpandTriggers, "When to expand", "secNotchExpandTriggers")
        XCTAssertEqual(l10n.lblExpandOnNotification, "On notification", "lblExpandOnNotification")
        XCTAssertEqual(l10n.lblExpandOnTaskCompletion, "On task completion", "lblExpandOnTaskCompletion")
        XCTAssertEqual(l10n.lblExpandOnIdlePrompt, "On idle / waiting for input", "lblExpandOnIdlePrompt")
        XCTAssertEqual(l10n.lblExpandOnNotificationMessage, "On notification message", "lblExpandOnNotificationMessage")
        XCTAssertEqual(l10n.lblExpandOnInteractiveTool, "On interactive input (Gemini only)", "lblExpandOnInteractiveTool")
        XCTAssertEqual(l10n.lblExpandOnApprovalRequest, "On approval request", "lblExpandOnApprovalRequest")
        XCTAssertEqual(l10n.lblExpandOnQuestionResponse, "On question response", "lblExpandOnQuestionResponse")
        XCTAssertEqual(l10n.hintExpandOnNotification, "Expand when a notification event occurs. Use the sub-options to choose which kinds.", "hintExpandOnNotification")
        XCTAssertEqual(l10n.hintExpandOnTaskCompletion, "When an agent finishes its task.", "hintExpandOnTaskCompletion")
        XCTAssertEqual(l10n.hintExpandOnIdlePrompt, "When the agent is done and waiting for the next prompt.", "hintExpandOnIdlePrompt")
        XCTAssertEqual(l10n.hintExpandOnNotificationMessage, "When a notification includes a question or message from the agent.", "hintExpandOnNotificationMessage")
        XCTAssertEqual(l10n.hintExpandOnInteractiveTool, "Gemini only — when an interactive tool (e.g. bash) is waiting for terminal input.", "hintExpandOnInteractiveTool")
        XCTAssertEqual(l10n.hintExpandOnApprovalRequest, "When a tool approval request is received.", "hintExpandOnApprovalRequest")
        XCTAssertEqual(l10n.hintExpandOnQuestionResponse, "When the agent sends a question and waits for a response.", "hintExpandOnQuestionResponse")
        XCTAssertEqual(l10n.secNotchCharacters, "Buddies", "secNotchCharacters")
        XCTAssertEqual(l10n.lblLeftCharacter, "Left Buddy", "lblLeftCharacter")
        XCTAssertEqual(l10n.lblRightCharacter, "Right Buddy", "lblRightCharacter")
        XCTAssertEqual(l10n.lblCharacter, "Buddy", "lblCharacter")
        XCTAssertEqual(l10n.lblRandomIncludes, "Random Buddies", "lblRandomIncludes")
        XCTAssertEqual(l10n.lblCharacterHorizontalInset(7), "Buddy horizontal position: 7 px", "lblCharacterHorizontalInset")
        XCTAssertEqual(l10n.lblCharacterVerticalOffset(7), "Buddy vertical position: 7 px", "lblCharacterVerticalOffset")
        XCTAssertEqual(l10n.lblNotchCenterText, "Center text", "lblNotchCenterText")
        XCTAssertEqual(l10n.secRequests, "Requests", "secRequests")
        XCTAssertEqual(l10n.lblRequestDisplay, "Request display", "lblRequestDisplay")
        XCTAssertEqual(l10n.secAutoApprovals, "Automatic approvals", "secAutoApprovals")
        XCTAssertEqual(l10n.lblAutoSafe, "Auto-approve safe/read-only tools", "lblAutoSafe")
        XCTAssertEqual(l10n.lblGeminiEmulate, "Show approval for risky tools (Gemini / Antigravity)", "lblGeminiEmulate")
        XCTAssertEqual(l10n.secPermissionTimeout, "Permission timeout", "secPermissionTimeout")
        XCTAssertEqual(l10n.lblPermissionTimeout(7), "Auto-pass after 7 seconds", "lblPermissionTimeout")
        XCTAssertEqual(l10n.secReplayRetention, "Replay log retention", "secReplayRetention")
        XCTAssertEqual(l10n.lblReplayRetention(7), "Replay log: 7 days", "lblReplayRetention")
        XCTAssertEqual(l10n.secFallback, "Transport failure fallback", "secFallback")
        XCTAssertEqual(l10n.lblFallbackPolicy, "Fallback policy", "lblFallbackPolicy")
        XCTAssertEqual(l10n.lblSessionApproval, "Session approval", "lblSessionApproval")
        XCTAssertEqual(l10n.lblPersistentDest, "Persistent approval scope", "lblPersistentDest")
        XCTAssertEqual(l10n.warnProjectSettings, "Project settings can be committed to the repository. Review changes before committing.", "warnProjectSettings")
        XCTAssertEqual(l10n.descCodex, "Codex session approval will use DevIsland-managed cache and persistent SQLite rules in later phases.", "descCodex")
        XCTAssertEqual(l10n.descGemini, "Prompts for approval on risky tools even when running with --auto-approve or --yolo.", "descGemini")
        XCTAssertEqual(l10n.secTransport, "Transport", "secTransport")
        XCTAssertEqual(l10n.lblTransport, "Transport", "lblTransport")
        XCTAssertEqual(l10n.descTransport, "Transport changes are written to the bridge runtime config. Restart DevIsland after switching listener transports.", "descTransport")
        XCTAssertEqual(l10n.secTCP, "TCP", "secTCP")
        XCTAssertEqual(l10n.lblPort, "Port", "lblPort")
        XCTAssertEqual(l10n.secUnixSocket, "Unix domain socket", "secUnixSocket")
        XCTAssertEqual(l10n.lblSocketPath, "Socket path", "lblSocketPath")
        XCTAssertEqual(l10n.lblFallbackTCP, "Fallback to TCP loopback", "lblFallbackTCP")
        XCTAssertEqual(l10n.secTimeouts, "Timeouts", "secTimeouts")
        XCTAssertEqual(l10n.lblConnectTimeout, "Connect timeout", "lblConnectTimeout")
        XCTAssertEqual(l10n.lblResponseTimeout, "Response timeout", "lblResponseTimeout")
        XCTAssertEqual(l10n.labelSeconds(7), "7 seconds", "labelSeconds")
        XCTAssertEqual(l10n.secTokenSecurity, "Token security", "secTokenSecurity")
        XCTAssertEqual(l10n.warnGraceMode, "IPC token file not found — running in grace mode. All incoming connections are accepted without authentication.", "warnGraceMode")
        XCTAssertEqual(l10n.hintGraceModeResolve, "Re-install the bridge to generate a token file.", "hintGraceModeResolve")
        XCTAssertEqual(l10n.secOpenPeonSoundPacks, "Sound packs", "secOpenPeonSoundPacks")
        XCTAssertEqual(l10n.lblOpenPeonEnable, "Enable sounds", "lblOpenPeonEnable")
        XCTAssertEqual(l10n.phOpenPeonPacksFolder, "Packs folder", "phOpenPeonPacksFolder")
        XCTAssertEqual(l10n.btnReload, "Reload", "btnReload")
        XCTAssertEqual(l10n.btnOpen, "Open", "btnOpen")
        XCTAssertEqual(l10n.btnPlayPreview, "Play preview", "btnPlayPreview")
        XCTAssertEqual(l10n.lblOpenPeonActivePack, "Active pack", "lblOpenPeonActivePack")
        XCTAssertEqual(l10n.lblOpenPeonFirstValidPack, "First valid pack", "lblOpenPeonFirstValidPack")
        XCTAssertEqual(l10n.lblOpenPeonNoPacks, "No sound packs found.", "lblOpenPeonNoPacks")
        XCTAssertEqual(l10n.lblOpenPeonNoSoundFile, "No sound file for this event", "lblOpenPeonNoSoundFile")
        XCTAssertEqual(l10n.secOpenPeonPlayback, "Playback", "secOpenPeonPlayback")
        XCTAssertEqual(l10n.lblOpenPeonMasterVolume, "Master volume", "lblOpenPeonMasterVolume")
        XCTAssertEqual(l10n.lblOpenPeonDebounce(7), "Debounce: 7 ms", "lblOpenPeonDebounce")
        XCTAssertEqual(l10n.secOpenPeonCategories, "Categories", "secOpenPeonCategories")
        XCTAssertEqual(l10n.secOpenPeonValidation, "Validation", "secOpenPeonValidation")
        XCTAssertEqual(l10n.lblOpenPeonValid, "Valid", "lblOpenPeonValid")
        XCTAssertEqual(l10n.errOpenPeonReadPacks("path"), "Could not read path", "errOpenPeonReadPacks")
        XCTAssertEqual(l10n.cespSessionStart, "Session start", "cespSessionStart")
        XCTAssertEqual(l10n.cespTaskAcknowledge, "Task acknowledge", "cespTaskAcknowledge")
        XCTAssertEqual(l10n.cespTaskComplete, "Task complete", "cespTaskComplete")
        XCTAssertEqual(l10n.cespTaskError, "Task error", "cespTaskError")
        XCTAssertEqual(l10n.cespInputRequired, "Input required", "cespInputRequired")
        XCTAssertEqual(l10n.cespResourceLimit, "Resource limit", "cespResourceLimit")
        XCTAssertEqual(l10n.cespUserSpam, "User spam", "cespUserSpam")
        XCTAssertEqual(l10n.cespSessionEnd, "Session end", "cespSessionEnd")
        XCTAssertEqual(l10n.cespTaskProgress, "Task progress", "cespTaskProgress")
        XCTAssertEqual(l10n.secPTYWrapper, "PTY Wrapper", "secPTYWrapper")
        XCTAssertEqual(l10n.lblPTYEnable, "Enable PTY logging and auto-inject", "lblPTYEnable")
        XCTAssertEqual(l10n.lblRetention(7), "Transcript retention: 7 days", "lblRetention")
        XCTAssertEqual(l10n.btnViewPTY, "View PTY Transcript…", "btnViewPTY")
        XCTAssertEqual(l10n.secAutoInject, "Auto-inject patterns", "secAutoInject")
        XCTAssertEqual(l10n.lblNoPatterns, "No patterns. Add one below.", "lblNoPatterns")
        XCTAssertEqual(l10n.phPattern, "Pattern (substring)", "phPattern")
        XCTAssertEqual(l10n.phResponse, "Response text", "phResponse")
        XCTAssertEqual(l10n.btnAdd, "Add", "btnAdd")
        XCTAssertEqual(l10n.secUsage, "Usage", "secUsage")
        XCTAssertEqual(l10n.descPTYUsage, "Run a CLI agent through the PTY wrapper:", "descPTYUsage")
        XCTAssertEqual(l10n.descPTYHooks, "The script forwards PTYOutput hook events to the app.", "descPTYHooks")
        XCTAssertEqual(l10n.secCodexRules, "Codex persistent SQLite rules", "secCodexRules")
        XCTAssertEqual(l10n.phToolName, "Tool name", "phToolName")
        XCTAssertEqual(l10n.lblAction, "Action", "lblAction")
        XCTAssertEqual(l10n.lblAllow, "Allow", "lblAllow")
        XCTAssertEqual(l10n.lblDeny, "Deny", "lblDeny")
        XCTAssertEqual(l10n.btnExportSnapshot, "Export Snapshot", "btnExportSnapshot")
        XCTAssertEqual(l10n.lblNoCodexRules, "No Codex persistent SQLite rules are configured.", "lblNoCodexRules")
        XCTAssertEqual(l10n.secGlobalRules, "Global auto-approval tools", "secGlobalRules")
        XCTAssertEqual(l10n.descGlobalRules, "These existing DevIsland rules are checked for every session before showing an approval prompt.", "descGlobalRules")
        XCTAssertEqual(l10n.alertAddGlobalToolTitle, "Add Global Auto-Approval Tool", "alertAddGlobalToolTitle")
        XCTAssertEqual(l10n.alertAddGlobalToolMsg, "Enter the tool name (e.g. read_file) to auto-approve in all sessions.", "alertAddGlobalToolMsg")
        XCTAssertEqual(l10n.alertAddSessionToolTitle, "Add Session Auto-Approval Tool", "alertAddSessionToolTitle")
        XCTAssertEqual(l10n.alertAddSessionToolMsg("id"), "Enter the tool name to auto-approve in session id.", "alertAddSessionToolMsg")
        XCTAssertEqual(l10n.btnAddManually, "Add manually…", "btnAddManually")
        XCTAssertEqual(l10n.btnAddFromList, "Add from list", "btnAddFromList")
        XCTAssertEqual(l10n.lblNoGlobalTools, "No global auto-approval tools are configured.", "lblNoGlobalTools")
        XCTAssertEqual(l10n.btnRemoveAllGlobal, "Remove all global tools", "btnRemoveAllGlobal")
        XCTAssertEqual(l10n.secSessionRules, "Session auto-approval tools", "secSessionRules")
        XCTAssertEqual(l10n.descSessionRules, "Session rules remain available until the corresponding active session is removed.", "descSessionRules")
        XCTAssertEqual(l10n.lblNoSessions, "No active sessions.", "lblNoSessions")
        XCTAssertEqual(l10n.lblNoSessionTools, "No session auto-approval tools are configured.", "lblNoSessionTools")
        XCTAssertEqual(l10n.btnRemoveAllSession, "Remove all session tools", "btnRemoveAllSession")
        XCTAssertEqual(l10n.lblSession("id", 7), "Session id (7 tools)", "lblSession")
        XCTAssertEqual(l10n.errSaveCodexRule("err"), "Failed to save Codex rule: err", "errSaveCodexRule")
        XCTAssertEqual(l10n.errDeleteCodexRule("err"), "Failed to delete Codex rule: err", "errDeleteCodexRule")
        XCTAssertEqual(l10n.errLoadCodexRules("err"), "Failed to load Codex rules: err", "errLoadCodexRules")
        XCTAssertEqual(l10n.exportedCodexRules(7, "path"), "Exported 7 Codex rules to path", "exportedCodexRules")
        XCTAssertEqual(l10n.errExportCodexRules("err"), "Failed to export Codex rules: err", "errExportCodexRules")
        XCTAssertEqual(l10n.addAllRisk("name"), "Add all name tools", "addAllRisk")
        XCTAssertEqual(l10n.monitorMain(), "Main monitor", "monitorMain")
        XCTAssertEqual(l10n.monitorN(7), "Monitor 7", "monitorN")
        XCTAssertEqual(l10n.notchAuto, "Automatic", "notchAuto")
        XCTAssertEqual(l10n.notchMain, "Main monitor", "notchMain")
        XCTAssertEqual(l10n.notchMouse, "Monitor with mouse", "notchMouse")
        XCTAssertEqual(l10n.notchFocused, "Monitor with focus", "notchFocused")
        XCTAssertEqual(l10n.notchSpecific, "Selected monitor", "notchSpecific")
        XCTAssertEqual(l10n.notchCharacterHidden, "Hidden", "notchCharacterHidden")
        XCTAssertEqual(l10n.notchCharacterRandom, "Random", "notchCharacterRandom")
        XCTAssertEqual(l10n.notchCharacterSpecific, "Specific", "notchCharacterSpecific")
        XCTAssertEqual(l10n.notchAutoCollapseOff, "Off", "notchAutoCollapseOff")
        XCTAssertEqual(l10n.reqNotch, "Island display", "reqNotch")
        XCTAssertEqual(l10n.reqFocused, "Focus display", "reqFocused")
        XCTAssertEqual(l10n.reqMouse, "Mouse display", "reqMouse")
        XCTAssertEqual(l10n.modeNative, "Native Claude permissions", "modeNative")
        XCTAssertEqual(l10n.modeCache, "DevIsland-managed session cache", "modeCache")
        XCTAssertEqual(l10n.modeHybrid, "Hybrid", "modeHybrid")
        XCTAssertEqual(l10n.detailNative, "Recommended. Claude manages approvals. Most compatible.", "detailNative")
        XCTAssertEqual(l10n.detailCache, "DevIsland remembers approved tools for the session. Won't ask again.", "detailCache")
        XCTAssertEqual(l10n.detailHybrid, "Uses Claude permissions when available, falls back to DevIsland.", "detailHybrid")
        XCTAssertEqual(l10n.destLocal, "Project local", "destLocal")
        XCTAssertEqual(l10n.destProject, "Project shared", "destProject")
        XCTAssertEqual(l10n.destUser, "User-wide", "destUser")
        XCTAssertEqual(l10n.detailDestLocal, "Applies to this project only. Not committed to git. (.claude/settings.local.json)", "detailDestLocal")
        XCTAssertEqual(l10n.detailDestProject, "Shared with your team. Can be committed to git. (.claude/settings.json)", "detailDestProject")
        XCTAssertEqual(l10n.detailDestUser, "Applies across all projects. (~/.claude/settings.json)", "detailDestUser")
        XCTAssertEqual(l10n.transportTCP, "TCP loopback", "transportTCP")
        XCTAssertEqual(l10n.transportUnix, "Unix domain socket", "transportUnix")
        XCTAssertEqual(l10n.fallbackPass, "Pass (let CLI decide)", "fallbackPass")
        XCTAssertEqual(l10n.fallbackDeny, "Deny", "fallbackDeny")
        XCTAssertEqual(l10n.fleetTitle, "Fleet Radar", "fleetTitle")
        XCTAssertEqual(l10n.fleetEmptyState, "Start a supported agent session to see it here.", "fleetEmptyState")
        XCTAssertEqual(l10n.fleetRefreshing, "Refreshing Fleet Radar", "fleetRefreshing")
        XCTAssertEqual(l10n.fleetActiveCardsCount(1), "1 active card", "fleetActiveCardsCount(singular)")
        XCTAssertEqual(l10n.fleetActiveCardsCount(7), "7 active cards", "fleetActiveCardsCount")
        XCTAssertEqual(l10n.fleetWorktreesCount(1), "1 worktree", "fleetWorktreesCount(singular)")
        XCTAssertEqual(l10n.fleetWorktreesCount(7), "7 worktrees", "fleetWorktreesCount")
        XCTAssertEqual(l10n.fleetOverlapPairsCount(1), "1 overlap pair", "fleetOverlapPairsCount(singular)")
        XCTAssertEqual(l10n.fleetOverlapPairsCount(7), "7 overlap pairs", "fleetOverlapPairsCount")
        XCTAssertEqual(l10n.fleetUpdated, "Updated", "fleetUpdated")
        XCTAssertEqual(l10n.fleetRefresh, "Refresh", "fleetRefresh")
        XCTAssertEqual(l10n.fleetRefreshHelp, "Refresh all Git context, ignoring the cache", "fleetRefreshHelp")
        XCTAssertEqual(l10n.fleetAttentionNeedsDecision, "Needs decision", "fleetAttentionNeedsDecision")
        XCTAssertEqual(l10n.fleetAttentionBlocked, "Blocked", "fleetAttentionBlocked")
        XCTAssertEqual(l10n.fleetAttentionOverlapRisk, "Overlap risk", "fleetAttentionOverlapRisk")
        XCTAssertEqual(l10n.fleetAttentionUnread, "Unread", "fleetAttentionUnread")
        XCTAssertEqual(l10n.fleetAttentionLive, "Live", "fleetAttentionLive")
        XCTAssertEqual(l10n.fleetAttention(.needsDecision), "Needs decision", "fleetAttention(needsDecision)")
        XCTAssertEqual(l10n.fleetAttention(.blocked), "Blocked", "fleetAttention(blocked)")
        XCTAssertEqual(l10n.fleetAttention(.overlapRisk), "Overlap risk", "fleetAttention(overlapRisk)")
        XCTAssertEqual(l10n.fleetAttention(.unread), "Unread", "fleetAttention(unread)")
        XCTAssertEqual(l10n.fleetAttention(.live), "Live", "fleetAttention(live)")
        XCTAssertEqual(l10n.fleetClean, "Clean", "fleetClean")
        XCTAssertEqual(l10n.fleetDirtyCount(1), "Dirty · 1 file", "fleetDirtyCount(singular)")
        XCTAssertEqual(l10n.fleetDirtyCount(7), "Dirty · 7 files", "fleetDirtyCount")
        XCTAssertEqual(l10n.fleetUnmerged, "Unmerged", "fleetUnmerged")
        XCTAssertEqual(l10n.fleetStale, "Stale", "fleetStale")
        XCTAssertEqual(l10n.fleetUnavailable, "Unavailable", "fleetUnavailable")
        XCTAssertEqual(l10n.fleetWorkspaceUnavailable, "Workspace unavailable", "fleetWorkspaceUnavailable")
        XCTAssertEqual(l10n.fleetNotRepository, "Not a Git repository", "fleetNotRepository")
        XCTAssertEqual(l10n.fleetGitContextUnavailable, "Git context unavailable", "fleetGitContextUnavailable")
        XCTAssertEqual(l10n.fleetRetry, "Retry", "fleetRetry")
        XCTAssertEqual(l10n.fleetOverlapRisk, "Overlap risk", "fleetOverlapRisk")
        XCTAssertEqual(l10n.fleetOverlapCount(1), "1 overlap", "fleetOverlapCount(singular)")
        XCTAssertEqual(l10n.fleetOverlapCount(7), "7 overlaps", "fleetOverlapCount")
        XCTAssertEqual(l10n.fleetFilesCount(1), "1 file", "fleetFilesCount(singular)")
        XCTAssertEqual(l10n.fleetFilesCount(7), "7 files", "fleetFilesCount")
        XCTAssertEqual(l10n.fleetOverlapDetails, "Overlap Details", "fleetOverlapDetails")
        XCTAssertEqual(l10n.fleetOverlapDetailsHelp, "Show overlapping paths by worktree", "fleetOverlapDetailsHelp")
        XCTAssertEqual(l10n.fleetMoreOverlaps(1), "+1 more overlap", "fleetMoreOverlaps(singular)")
        XCTAssertEqual(l10n.fleetMoreOverlaps(7), "+7 more overlaps", "fleetMoreOverlaps")
        XCTAssertEqual(l10n.fleetMoreFiles(1), "+1 more file", "fleetMoreFiles(singular)")
        XCTAssertEqual(l10n.fleetMoreFiles(7), "+7 more files", "fleetMoreFiles")
        XCTAssertEqual(l10n.fleetOverlapDisclaimer, "This is path overlap, not a guaranteed merge conflict.", "fleetOverlapDisclaimer")
        XCTAssertEqual(l10n.fleetRecentActivity, "Recent activity", "fleetRecentActivity")
        XCTAssertEqual(l10n.fleetNoRecentActivity, "No recent activity", "fleetNoRecentActivity")
        XCTAssertEqual(l10n.fleetSubagents, "Sub-agents", "fleetSubagents")
        XCTAssertEqual(l10n.fleetOrphanSubagent, "Orphan sub-agent", "fleetOrphanSubagent")
        XCTAssertEqual(l10n.fleetMoreSubagents(1), "+1 more", "fleetMoreSubagents(singular)")
        XCTAssertEqual(l10n.fleetMoreSubagents(7), "+7 more", "fleetMoreSubagents")
        XCTAssertEqual(l10n.fleetShowFewer, "Show fewer", "fleetShowFewer")
        XCTAssertEqual(l10n.fleetShowDetail, "Show Detail", "fleetShowDetail")
        XCTAssertEqual(l10n.fleetShowDetailHelp, "Show this session in the Island without focusing the terminal", "fleetShowDetailHelp")
        XCTAssertEqual(l10n.fleetFocusTerminal, "Focus Terminal", "fleetFocusTerminal")
        XCTAssertEqual(l10n.fleetFocusTerminalHelp, "Focus the terminal; a displayed approval may return to the terminal.", "fleetFocusTerminalHelp")
        XCTAssertEqual(l10n.fleetOpenInFinder, "Open in Finder", "fleetOpenInFinder")
        XCTAssertEqual(l10n.fleetOpenInFinderHelp, "Open the workspace in Finder", "fleetOpenInFinderHelp")
        XCTAssertEqual(l10n.fleetCopyPath, "Copy Path", "fleetCopyPath")
        XCTAssertEqual(l10n.fleetCopyPathHelp, "Copy the workspace path", "fleetCopyPathHelp")
        XCTAssertEqual(
            l10n.fleetCardAccessibility("title", "provider", "attention", "branch", "dirty", "overlap"),
            "title, provider, attention, branch branch, dirty, overlap",
            "fleetCardAccessibility"
        )
        XCTAssertEqual(l10n.popOutWindow, "Pop out message window", "popOutWindow")
        XCTAssertEqual(l10n.sessionEnded, "Session ended", "sessionEnded")
        XCTAssertEqual(l10n.msgWaiting, "Waiting for message…", "msgWaiting")
        XCTAssertEqual(l10n.approvingOtherSession, "Approving another session…", "approvingOtherSession")
        XCTAssertEqual(l10n.notchApprovalRequired, "Approval Required", "notchApprovalRequired")
        XCTAssertEqual(l10n.notchNotification, "Notification", "notchNotification")
        XCTAssertEqual(l10n.notchMonitoring, "Monitoring", "notchMonitoring")
        XCTAssertEqual(l10n.notchActiveAction, "ACTIVE ACTION", "notchActiveAction")
        XCTAssertEqual(l10n.notchAgentSessions, "AGENT SESSIONS", "notchAgentSessions")
        XCTAssertEqual(l10n.notchListening, "Listening for AI Agents…", "notchListening")
        XCTAssertEqual(l10n.terminalWaiting, "Waiting for terminal confirmation…", "terminalWaiting")
        XCTAssertEqual(l10n.terminalCheckMsg("tool"), "Check terminal window (tool)", "terminalCheckMsg")
        XCTAssertEqual(l10n.notchSessions, "Sessions", "notchSessions")
        XCTAssertEqual(l10n.notchFocus, "Focus", "notchFocus")
        XCTAssertEqual(l10n.notchDenyRequest, "Deny Request", "notchDenyRequest")
        XCTAssertEqual(l10n.notchApprove, "Approve", "notchApprove")
        XCTAssertEqual(l10n.notchAutoApproveSession, "Auto-Approve for this Session", "notchAutoApproveSession")
        XCTAssertEqual(l10n.notchAlwaysAutoApprove, "Always Auto-Approve (Global)", "notchAlwaysAutoApprove")
        XCTAssertEqual(l10n.notchAlwaysAllowSuggestion, "Always allow this tool?", "notchAlwaysAllowSuggestion")
        XCTAssertEqual(l10n.notchAlwaysAllowSuggestionHelp("tool"), "You've approved 'tool' multiple times. Click to add a permanent allow rule.", "notchAlwaysAllowSuggestionHelp")
        XCTAssertEqual(l10n.notchFocusTerminal, "Focus Terminal", "notchFocusTerminal")
        XCTAssertEqual(l10n.notchDismiss, "Dismiss", "notchDismiss")
        XCTAssertEqual(l10n.notchUnknown, "Unknown", "notchUnknown")
        XCTAssertEqual(l10n.helpOpenSettings, "Open settings", "helpOpenSettings")
        XCTAssertEqual(l10n.helpFocusTerminal, "Focus terminal", "helpFocusTerminal")
        XCTAssertEqual(l10n.helpDismissSession, "Dismiss session", "helpDismissSession")
        XCTAssertEqual(l10n.menuOpenInFinder, "Open in Finder", "menuOpenInFinder")
        XCTAssertEqual(l10n.menuCopyPath, "Copy Path", "menuCopyPath")
        XCTAssertEqual(l10n.menuCopyResumeCommand, "Copy Resume Command", "menuCopyResumeCommand")
        XCTAssertEqual(l10n.menuRenameSession, "Rename…", "menuRenameSession")
        XCTAssertEqual(l10n.menuEditSessionDescription, "Edit Description…", "menuEditSessionDescription")
        XCTAssertEqual(l10n.menuAddFavorite, "Add to Favorites", "menuAddFavorite")
        XCTAssertEqual(l10n.menuRemoveFavorite, "Remove from Favorites", "menuRemoveFavorite")
        XCTAssertEqual(l10n.renameSessionTitle, "Rename Session", "renameSessionTitle")
        XCTAssertEqual(l10n.renameSessionConfirm, "Rename", "renameSessionConfirm")
        XCTAssertEqual(l10n.renameSessionPlaceholder, "Session name", "renameSessionPlaceholder")
        XCTAssertEqual(l10n.sessionDescriptionTitle, "Session Description", "sessionDescriptionTitle")
        XCTAssertEqual(l10n.sessionDescriptionConfirm, "Save", "sessionDescriptionConfirm")
        XCTAssertEqual(l10n.btnCancel, "Cancel", "btnCancel")
        XCTAssertEqual(l10n.renameSessionHint("id"), "Enter a name for session id. Leave empty to reset.", "renameSessionHint")
        XCTAssertEqual(l10n.sessionDescriptionHint("id"), "Add notes for session id. Leave empty to clear.", "sessionDescriptionHint")
        XCTAssertEqual(l10n.menuOpenInTerminal, "Open in Terminal", "menuOpenInTerminal")
        XCTAssertEqual(l10n.menuTerminalAuto("name"), "Auto (name)", "menuTerminalAuto")
        XCTAssertEqual(l10n.menuStartNewSession, "New Session Here", "menuStartNewSession")
        XCTAssertEqual(l10n.helpDismissPending, "Dismiss session and pass pending request to terminal", "helpDismissPending")
        XCTAssertEqual(l10n.tasksQueued(7), "7 tasks queued", "tasksQueued")
        XCTAssertEqual(l10n.timeJustNow(), "Just now", "timeJustNow")
        XCTAssertEqual(l10n.timeSecsAgo(7), "7s ago", "timeSecsAgo")
        XCTAssertEqual(l10n.timeMinsAgo(7), "7m ago", "timeMinsAgo")
        XCTAssertEqual(l10n.historyTabSessions, "Sessions", "historyTabSessions")
        XCTAssertEqual(l10n.historyTabInsights, "Insights", "historyTabInsights")
        XCTAssertEqual(l10n.insightsTodaySessions, "Today", "insightsTodaySessions")
        XCTAssertEqual(l10n.insightsTotalSessions, "Total (retention)", "insightsTotalSessions")
        XCTAssertEqual(l10n.insightsAvgDuration, "Avg. Duration", "insightsAvgDuration")
        XCTAssertEqual(l10n.insightsApprovals, "Approval Breakdown", "insightsApprovals")
        XCTAssertEqual(l10n.insightsManualApproved, "Approved", "insightsManualApproved")
        XCTAssertEqual(l10n.insightsManualDenied, "Denied", "insightsManualDenied")
        XCTAssertEqual(l10n.insightsAutoApproved, "Auto", "insightsAutoApproved")
        XCTAssertEqual(l10n.insightsAutoDenied, "Policy Denied", "insightsAutoDenied")
        XCTAssertEqual(l10n.insightsTopTools, "Most Approved Tools", "insightsTopTools")
        XCTAssertEqual(l10n.insightsNoData, "No data yet", "insightsNoData")
        XCTAssertEqual(l10n.insightsRetentionNote, "Based on replay log retention window", "insightsRetentionNote")
        XCTAssertEqual(l10n.insightsDuration("s"), "avg s", "insightsDuration")
        XCTAssertEqual(l10n.historySearch, "Search sessions…", "historySearch")
        XCTAssertEqual(l10n.historyEmpty, "No sessions", "historyEmpty")
        XCTAssertEqual(l10n.historyFilterAll, "All", "historyFilterAll")
        XCTAssertEqual(l10n.historyFilterFavorites, "Favorites", "historyFilterFavorites")
        XCTAssertEqual(l10n.historyRefresh, "Refresh", "historyRefresh")
        XCTAssertEqual(l10n.historyColFavorite, "Favorite", "historyColFavorite")
        XCTAssertEqual(l10n.historyColStatus, "Status", "historyColStatus")
        XCTAssertEqual(l10n.historyColAgent, "Agent", "historyColAgent")
        XCTAssertEqual(l10n.historyColPath, "Path", "historyColPath")
        XCTAssertEqual(l10n.historyColLabel, "Name", "historyColLabel")
        XCTAssertEqual(l10n.historyColDescription, "Description", "historyColDescription")
        XCTAssertEqual(l10n.historyColTitle, "Terminal", "historyColTitle")
        XCTAssertEqual(l10n.historyColEnded, "Ended", "historyColEnded")
        XCTAssertEqual(l10n.historyColSession, "Session ID", "historyColSession")
        XCTAssertEqual(l10n.historyStatusLive, "Live", "historyStatusLive")
        XCTAssertEqual(l10n.historyStatusEnded, "Ended", "historyStatusEnded")
        XCTAssertEqual(l10n.historyCount(7), "7 sessions", "historyCount")
        XCTAssertEqual(l10n.statusPending, "Pending", "statusPending")
        XCTAssertEqual(l10n.statusBypassed, "Bypassed", "statusBypassed")
        XCTAssertEqual(l10n.statusAutoApproved, "Auto-Approved", "statusAutoApproved")
        XCTAssertEqual(l10n.statusPolicyApproved, "Policy-Approved", "statusPolicyApproved")
        XCTAssertEqual(l10n.statusPolicyDenied, "Policy-Denied", "statusPolicyDenied")
        XCTAssertEqual(l10n.statusAutoEdit, "Auto-Edit", "statusAutoEdit")
        XCTAssertEqual(l10n.notifTaskCompleteBody(""), "Agent finished.", "notifTaskCompleteBody(empty)")
        XCTAssertEqual(l10n.notifTaskCompleteBody("Build"), "Build complete", "notifTaskCompleteBody(nonempty)")
    }

    func testKoreanCatalogMatchesLegacy() {
        l10n.language = .korean
        XCTAssertEqual(l10n.menuNoPending, "대기 중인 요청 없음", "menuNoPending")
        XCTAssertEqual(l10n.menuPending, "요청 대기 중", "menuPending")
        XCTAssertEqual(l10n.menuFocusTerminal, "터미널 포커스", "menuFocusTerminal")
        XCTAssertEqual(l10n.menuApprove, "승인  ⌘⇧Y", "menuApprove")
        XCTAssertEqual(l10n.menuDeny, "거부  ⌘⇧N", "menuDeny")
        XCTAssertEqual(l10n.menuSettings, "설정…", "menuSettings")
        XCTAssertEqual(l10n.menuApprovalRules, "승인 규칙…", "menuApprovalRules")
        XCTAssertEqual(l10n.menuReplayLog, "재실행 로그…", "menuReplayLog")
        XCTAssertEqual(l10n.menuPTYTranscript, "PTY 트랜스크립트…", "menuPTYTranscript")
        XCTAssertEqual(l10n.menuSessionHistory, "세션 기록…", "menuSessionHistory")
        XCTAssertEqual(l10n.menuInstallHooks, "훅 설치 / 수리", "menuInstallHooks")
        XCTAssertEqual(l10n.menuInstallAll, "전부 설치 (Claude · Codex · Gemini · Antigravity)", "menuInstallAll")
        XCTAssertEqual(l10n.menuInstallClaude, "Claude Code만 설치…", "menuInstallClaude")
        XCTAssertEqual(l10n.menuInstallCodex, "Codex CLI만 설치…", "menuInstallCodex")
        XCTAssertEqual(l10n.menuInstallGemini, "Gemini CLI만 설치…", "menuInstallGemini")
        XCTAssertEqual(l10n.menuInstallAntigravity, "Antigravity CLI만 설치…", "menuInstallAntigravity")
        XCTAssertEqual(l10n.menuRemoveAll, "전부 제거 (Claude · Codex · Gemini · Antigravity)", "menuRemoveAll")
        XCTAssertEqual(l10n.menuRemoveClaude, "Claude Code만 제거…", "menuRemoveClaude")
        XCTAssertEqual(l10n.menuRemoveCodex, "Codex CLI만 제거…", "menuRemoveCodex")
        XCTAssertEqual(l10n.menuRemoveGemini, "Gemini CLI만 제거…", "menuRemoveGemini")
        XCTAssertEqual(l10n.menuRemoveAntigravity, "Antigravity CLI만 제거…", "menuRemoveAntigravity")
        XCTAssertEqual(l10n.menuAccessibility, "접근성 권한 요청…", "menuAccessibility")
        XCTAssertEqual(l10n.menuCheckForUpdates, "업데이트 확인…", "menuCheckForUpdates")
        XCTAssertEqual(l10n.menuUpdateAvailable("v"), "업데이트 있음 (v)…", "menuUpdateAvailable")
        XCTAssertEqual(l10n.menuQuit, "DevIsland 종료", "menuQuit")
        XCTAssertEqual(l10n.alertAllInstalled, "전체 훅 설치 완료", "alertAllInstalled")
        XCTAssertEqual(l10n.alertClaudeInstalled, "Claude Code 설치 완료", "alertClaudeInstalled")
        XCTAssertEqual(l10n.alertClaudeInstallFailed, "Claude Code 설치 실패", "alertClaudeInstallFailed")
        XCTAssertEqual(l10n.alertCodexInstalled, "Codex CLI 설치 완료", "alertCodexInstalled")
        XCTAssertEqual(l10n.alertCodexInstallFailed, "Codex CLI 설치 실패", "alertCodexInstallFailed")
        XCTAssertEqual(l10n.alertGeminiInstalled, "Gemini CLI 설치 완료", "alertGeminiInstalled")
        XCTAssertEqual(l10n.alertGeminiInstallFailed, "Gemini CLI 설치 실패", "alertGeminiInstallFailed")
        XCTAssertEqual(l10n.alertAntigravityInstalled, "Antigravity CLI 설치 완료", "alertAntigravityInstalled")
        XCTAssertEqual(l10n.alertAntigravityInstallFailed, "Antigravity CLI 설치 실패", "alertAntigravityInstallFailed")
        XCTAssertEqual(l10n.alertInstallFailed, "설치 실패", "alertInstallFailed")
        XCTAssertEqual(l10n.alertAllInstalledMsg, "모든 브리지 훅이 설치되었습니다.\n각 CLI 세션을 재시작해주세요.", "alertAllInstalledMsg")
        XCTAssertEqual(l10n.alertBridgeInstalled, "브리지가 설치되었습니다.\n세션을 재시작해주세요.", "alertBridgeInstalled")
        XCTAssertEqual(l10n.alertClaudeRestartMsg, "브리지가 설치되었습니다.\nClaude Code 세션을 재시작해주세요.", "alertClaudeRestartMsg")
        XCTAssertEqual(l10n.alertCodexRestartMsg, "브리지가 설치되었습니다.\nCodex CLI 세션을 재시작해주세요.", "alertCodexRestartMsg")
        XCTAssertEqual(l10n.alertGeminiRestartMsg, "브리지가 설치되었습니다.\nGemini CLI 세션을 재시작해주세요.", "alertGeminiRestartMsg")
        XCTAssertEqual(l10n.alertAntigravityRestartMsg, "브리지가 설치되었습니다.\nAntigravity CLI 세션을 재시작해주세요.", "alertAntigravityRestartMsg")
        XCTAssertEqual(l10n.alertBundleNoScript, "앱 번들에서 브리지 스크립트를 찾을 수 없습니다.", "alertBundleNoScript")
        XCTAssertEqual(l10n.alertBundleNoHelper, "앱 번들에서 브리지 helper를 찾을 수 없습니다.", "alertBundleNoHelper")
        XCTAssertEqual(l10n.alertBundleNoManifest, "앱 번들에서 훅 이벤트 manifest를 찾을 수 없습니다.", "alertBundleNoManifest")
        XCTAssertEqual(l10n.alertBundleNoInstaller, "앱 번들에서 훅 설치 스크립트를 찾을 수 없습니다.", "alertBundleNoInstaller")
        XCTAssertEqual(l10n.alertBundleNoCodexWrapper, "앱 번들에서 Codex Auto-review 래퍼를 찾을 수 없습니다.", "alertBundleNoCodexWrapper")
        XCTAssertEqual(l10n.alertInstallScriptFailed("detail"), "훅 설치 스크립트 실패: detail", "alertInstallScriptFailed")
        XCTAssertEqual(l10n.alertBadJSON, "settings.json 파싱 실패: 유효하지 않은 JSON 형식입니다.", "alertBadJSON")
        XCTAssertEqual(l10n.alertBadFile("name"), "name 파싱 실패", "alertBadFile")
        XCTAssertEqual(l10n.alertAllRemoved, "전체 제거 완료", "alertAllRemoved")
        XCTAssertEqual(l10n.alertAllRemovedMsg, "모든 브리지 훅이 제거되었습니다.\n각 CLI 세션을 재시작해주세요.", "alertAllRemovedMsg")
        XCTAssertEqual(l10n.alertSomeRemoveFailed, "일부 제거 실패", "alertSomeRemoveFailed")
        XCTAssertEqual(l10n.alertClaudeRemoved, "Claude Code 제거 완료", "alertClaudeRemoved")
        XCTAssertEqual(l10n.alertClaudeRemoveFailed, "Claude Code 제거 실패", "alertClaudeRemoveFailed")
        XCTAssertEqual(l10n.alertCodexRemoved, "Codex CLI 제거 완료", "alertCodexRemoved")
        XCTAssertEqual(l10n.alertCodexRemoveFailed, "Codex CLI 제거 실패", "alertCodexRemoveFailed")
        XCTAssertEqual(l10n.alertGeminiRemoved, "Gemini CLI 제거 완료", "alertGeminiRemoved")
        XCTAssertEqual(l10n.alertGeminiRemoveFailed, "Gemini CLI 제거 실패", "alertGeminiRemoveFailed")
        XCTAssertEqual(l10n.alertAntigravityRemoved, "Antigravity CLI 제거 완료", "alertAntigravityRemoved")
        XCTAssertEqual(l10n.alertAntigravityRemoveFailed, "Antigravity CLI 제거 실패", "alertAntigravityRemoveFailed")
        XCTAssertEqual(l10n.alertHooksRemoved, "훅이 제거되었습니다.\n세션을 재시작해주세요.", "alertHooksRemoved")
        XCTAssertEqual(l10n.alertClaudeHooksRemoved, "훅이 제거되었습니다.\nClaude Code 세션을 재시작해주세요.", "alertClaudeHooksRemoved")
        XCTAssertEqual(l10n.alertCodexHooksRemoved, "훅이 제거되었습니다.\nCodex CLI 세션을 재시작해주세요.", "alertCodexHooksRemoved")
        XCTAssertEqual(l10n.alertGeminiHooksRemoved, "훅이 제거되었습니다.\nGemini CLI 세션을 재시작해주세요.", "alertGeminiHooksRemoved")
        XCTAssertEqual(l10n.alertAntigravityHooksRemoved, "훅이 제거되었습니다.\nAntigravity CLI 세션을 재시작해주세요.", "alertAntigravityHooksRemoved")
        XCTAssertEqual(l10n.alertOK, "확인", "alertOK")
        XCTAssertEqual(l10n.relocateTitle, "응용 프로그램 폴더로 이동하시겠습니까?", "relocateTitle")
        XCTAssertEqual(l10n.relocateMessage, "DevIsland를 응용 프로그램 폴더로 이동하여 계속 사용하시겠습니까?", "relocateMessage")
        XCTAssertEqual(l10n.relocateMoveBtn, "이동 및 다시 실행", "relocateMoveBtn")
        XCTAssertEqual(l10n.relocateLaterBtn, "나중에", "relocateLaterBtn")
        XCTAssertEqual(l10n.relocateFailTitle, "이동 실패", "relocateFailTitle")
        XCTAssertEqual(l10n.relocateNoPermMsg, "응용 프로그램 폴더에 쓰기 권한이 없습니다. Finder에서 직접 이동해주세요.", "relocateNoPermMsg")
        XCTAssertEqual(l10n.relocateErrMsg("err"), "앱을 이동하는 중 오류가 발생했습니다: err", "relocateErrMsg")
        XCTAssertEqual(l10n.dmgCleanTitle, "설치 파일을 정리하시겠습니까?", "dmgCleanTitle")
        XCTAssertEqual(l10n.dmgCleanMessage, "설치가 완료되었습니다. 사용 중인 설치 파일(DMG)을 꺼내고 정리하시겠습니까?", "dmgCleanMessage")
        XCTAssertEqual(l10n.dmgCleanBtn, "정리", "dmgCleanBtn")
        XCTAssertEqual(l10n.dmgNoBtn, "아니요", "dmgNoBtn")
        XCTAssertEqual(l10n.dmgEjectFailTitle, "꺼내기 실패", "dmgEjectFailTitle")
        XCTAssertEqual(l10n.dmgEjectFailMsg, "설치 파일을 꺼내는 중 오류가 발생했습니다. Finder에서 직접 꺼내주세요.", "dmgEjectFailMsg")
        XCTAssertEqual(l10n.updateAvailableTitle, "업데이트 가능", "updateAvailableTitle")
        XCTAssertEqual(l10n.updateChangeLogTitle, "릴리즈 노트 / 변경 로그", "updateChangeLogTitle")
        XCTAssertEqual(l10n.updateAvailableMsg("v"), "DevIsland v이(가) 출시되었습니다.\n설치 후 재실행하시겠습니까?", "updateAvailableMsg")
        XCTAssertEqual(l10n.updateInstallBtn, "설치 후 재실행", "updateInstallBtn")
        XCTAssertEqual(l10n.updateLaterBtn, "나중에", "updateLaterBtn")
        XCTAssertEqual(l10n.updateUpToDateTitle, "최신 버전", "updateUpToDateTitle")
        XCTAssertEqual(l10n.updateUpToDateMsg("v"), "DevIsland v이 최신 버전입니다.", "updateUpToDateMsg")
        XCTAssertEqual(l10n.updateDownloading, "다운로드 중…", "updateDownloading")
        XCTAssertEqual(l10n.updateInstalling, "설치 중…", "updateInstalling")
        XCTAssertEqual(l10n.updateRelaunching, "재실행 중…", "updateRelaunching")
        XCTAssertEqual(l10n.updateFailedTitle, "업데이트 실패", "updateFailedTitle")
        XCTAssertEqual(l10n.updateCheckFailedTitle, "업데이트 확인 실패", "updateCheckFailedTitle")
        XCTAssertEqual(l10n.updateInvalidResponseMsg, "GitHub에서 잘못된 응답을 받았습니다.", "updateInvalidResponseMsg")
        XCTAssertEqual(l10n.updateNoAssetMsg, "최신 릴리즈에서 DMG를 찾을 수 없습니다.", "updateNoAssetMsg")
        XCTAssertEqual(l10n.winSettings, "DevIsland 설정", "winSettings")
        XCTAssertEqual(l10n.winApprovalRules, "승인 규칙", "winApprovalRules")
        XCTAssertEqual(l10n.winReplayLog, "재실행 로그", "winReplayLog")
        XCTAssertEqual(l10n.winPTYTranscript, "PTY 트랜스크립트", "winPTYTranscript")
        XCTAssertEqual(l10n.winSessionHistory, "세션 기록", "winSessionHistory")
        XCTAssertEqual(l10n.tabGeneral, "일반", "tabGeneral")
        XCTAssertEqual(l10n.tabIsland, "아일랜드", "tabIsland")
        XCTAssertEqual(l10n.tabApproval, "승인", "tabApproval")
        XCTAssertEqual(l10n.tabProviders, "공급자", "tabProviders")
        XCTAssertEqual(l10n.tabBridge, "브리지 / IPC", "tabBridge")
        XCTAssertEqual(l10n.tabExperimental, "실험적", "tabExperimental")
        XCTAssertEqual(l10n.tabDiagnostics, "진단", "tabDiagnostics")
        XCTAssertEqual(l10n.tabIntegrations, "통합", "tabIntegrations")
        XCTAssertEqual(l10n.tabExtras, "부가기능", "tabExtras")
        XCTAssertEqual(l10n.tabAdvanced, "고급", "tabAdvanced")
        XCTAssertEqual(l10n.tabPlugins, "플러그인", "tabPlugins")
        XCTAssertEqual(l10n.secBridgeScript, "브리지 스크립트", "secBridgeScript")
        XCTAssertEqual(l10n.lblBridgeInstallPath, "설치 경로", "lblBridgeInstallPath")
        XCTAssertEqual(l10n.lblBridgeFileFound, "설치됨", "lblBridgeFileFound")
        XCTAssertEqual(l10n.lblBridgeFileNotFound, "없음", "lblBridgeFileNotFound")
        XCTAssertEqual(l10n.secHookStatus, "훅 설치 상태", "secHookStatus")
        XCTAssertEqual(l10n.lblHookInstalled, "설치됨", "lblHookInstalled")
        XCTAssertEqual(l10n.lblHookNotInstalled, "설치 안 됨", "lblHookNotInstalled")
        XCTAssertEqual(l10n.lblHookFileMissing, "파일 없음", "lblHookFileMissing")
        XCTAssertEqual(l10n.secLastEvent, "마지막 이벤트 수신", "secLastEvent")
        XCTAssertEqual(l10n.lblNoEventYet, "없음", "lblNoEventYet")
        XCTAssertEqual(l10n.secBridgeLog, "브리지 로그 (최근 20줄)", "secBridgeLog")
        XCTAssertEqual(l10n.secBridgeLogEmpty, "로그 파일 없음", "secBridgeLogEmpty")
        XCTAssertEqual(l10n.btnDiagRefresh, "새로 고침", "btnDiagRefresh")
        XCTAssertEqual(l10n.pluginsEmpty, "등록된 플러그인이 없습니다.", "pluginsEmpty")
        XCTAssertEqual(l10n.pluginsListHeader, "내장 플러그인", "pluginsListHeader")
        XCTAssertEqual(l10n.lblPluginSafemode, "세이프모드 — 반복 오류로 비활성화됨", "lblPluginSafemode")
        XCTAssertEqual(l10n.btnPluginReset, "초기화", "btnPluginReset")
        XCTAssertEqual(l10n.btnPluginResetStorage, "저장소 초기화", "btnPluginResetStorage")
        XCTAssertEqual(l10n.msgPluginResetStorageConfirm, "이 플러그인의 모든 저장 데이터를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.", "msgPluginResetStorageConfirm")
        XCTAssertEqual(l10n.pluginFailures(7), "오류: 7회", "pluginFailures")
        XCTAssertEqual(l10n.lblPluginSettings, "설정", "lblPluginSettings")
        XCTAssertEqual(l10n.secCaffeineStatus, "현재 상태", "secCaffeineStatus")
        XCTAssertEqual(l10n.secCaffeineBehavior, "동작", "secCaffeineBehavior")
        XCTAssertEqual(l10n.secCaffeineExcludedSSIDs, "예외 Wi-Fi 네트워크", "secCaffeineExcludedSSIDs")
        XCTAssertEqual(l10n.lblCaffeineEnabled, "Caffeine 사용", "lblCaffeineEnabled")
        XCTAssertEqual(l10n.lblCurrentSSID, "현재 Wi-Fi", "lblCurrentSSID")
        XCTAssertEqual(l10n.lblOnAC, "전원 연결", "lblOnAC")
        XCTAssertEqual(l10n.lblBatteryLevel, "배터리", "lblBatteryLevel")
        XCTAssertEqual(l10n.lblHoldingAssertion, "슬립 차단 중", "lblHoldingAssertion")
        XCTAssertEqual(l10n.btnAddSSID, "SSID 추가…", "btnAddSSID")
        XCTAssertEqual(l10n.lblScanNearbyWifi, "주변 Wi-Fi", "lblScanNearbyWifi")
        XCTAssertEqual(l10n.lblConnectedSSID, "연결됨", "lblConnectedSSID")
        XCTAssertEqual(l10n.lblManualSSIDEntry, "SSID 직접 입력", "lblManualSSIDEntry")
        XCTAssertEqual(l10n.lblScanFailed, "스캔 실패 (위치 권한 필요)", "lblScanFailed")
        XCTAssertEqual(l10n.lblScanErrorPermission, "Wi-Fi 스캔에 위치 권한이 필요합니다", "lblScanErrorPermission")
        XCTAssertEqual(l10n.lblScanErrorRadioOff, "Wi-Fi가 꺼져 있습니다", "lblScanErrorRadioOff")
        XCTAssertEqual(l10n.lblScanErrorUnknown("detail"), "스캔 실패: detail", "lblScanErrorUnknown")
        XCTAssertEqual(l10n.btnOpenLocationSettings, "시스템 설정 열기", "btnOpenLocationSettings")
        XCTAssertEqual(l10n.hintCaffeineRule, "켰을 때만 동작합니다. 전원 연결 시 슬립이 차단되며, 예외 Wi-Fi 또는 배터리 20% 이하에서는 항상 비활성화됩니다.", "hintCaffeineRule")
        XCTAssertEqual(l10n.secCaffeineSessionTimeout, "세션 유휴 타임아웃", "secCaffeineSessionTimeout")
        XCTAssertEqual(l10n.lblCaffeineSessionTimeoutEnabled, "세션 유휴 시 비활성화", "lblCaffeineSessionTimeoutEnabled")
        XCTAssertEqual(l10n.lblCaffeineSessionTimeoutMinutes(7), "타임아웃: 7분", "lblCaffeineSessionTimeoutMinutes")
        XCTAssertEqual(l10n.hintCaffeineSessionTimeout, "설정한 시간 동안 모든 세션이 유휴 또는 종료 상태이면 Caffeine이 자동으로 꺼집니다.", "hintCaffeineSessionTimeout")
        XCTAssertEqual(l10n.menuCaffeineToggle, "Caffeine", "menuCaffeineToggle")
        XCTAssertEqual(l10n.menuCaffeineOnAC, "슬립 차단 중 — AC 전원", "menuCaffeineOnAC")
        XCTAssertEqual(l10n.menuCaffeineOff, "비활성", "menuCaffeineOff")
        XCTAssertEqual(l10n.menuCaffeineOnBattery, "비활성 — 배터리 사용 중", "menuCaffeineOnBattery")
        XCTAssertEqual(l10n.menuCaffeineLowBattery, "비활성 — 배터리 부족", "menuCaffeineLowBattery")
        XCTAssertEqual(l10n.menuCaffeineExcludedSSID("ssid"), "비활성 — 예외 Wi-Fi (ssid)", "menuCaffeineExcludedSSID")
        XCTAssertEqual(l10n.menuCaffeineFailure(7), "슬립 차단 활성화 실패 (코드 7)", "menuCaffeineFailure")
        XCTAssertEqual(l10n.secAppIntegrations, "앱 통합", "secAppIntegrations")
        XCTAssertEqual(l10n.lblProcessVSCode, "VS Code 통합 활성화", "lblProcessVSCode")
        XCTAssertEqual(l10n.descProcessVSCode, "VS Code에서 실행 중인 세션의 hook 이벤트를 처리합니다.", "descProcessVSCode")
        XCTAssertEqual(l10n.lblProcessClaudeDesktop, "Claude 데스크탑 통합 활성화", "lblProcessClaudeDesktop")
        XCTAssertEqual(l10n.descProcessClaudeDesktop, "Claude 데스크탑에서 실행 중인 세션의 hook 이벤트를 처리합니다.", "descProcessClaudeDesktop")
        XCTAssertEqual(l10n.lblProcessCodexDesktop, "Codex 데스크탑 통합 활성화", "lblProcessCodexDesktop")
        XCTAssertEqual(l10n.descProcessCodexDesktop, "Codex 데스크탑에서 실행 중인 세션의 hook 이벤트를 처리합니다.", "descProcessCodexDesktop")
        XCTAssertEqual(l10n.btnResetAllSettings, "모든 설정 초기화", "btnResetAllSettings")
        XCTAssertEqual(l10n.secLanguage, "언어", "secLanguage")
        XCTAssertEqual(l10n.lblLanguage, "언어", "lblLanguage")
        XCTAssertEqual(l10n.secPreferredTerminal, "기본 터미널", "secPreferredTerminal")
        XCTAssertEqual(l10n.lblPreferredTerminal, "세션 열기", "lblPreferredTerminal")
        XCTAssertEqual(l10n.optTerminalSessionDefault, "세션 터미널 자동 선택", "optTerminalSessionDefault")
        XCTAssertEqual(l10n.hintPreferredTerminal, "새 터미널 창에서 세션을 열 때 사용합니다. 설정하지 않으면 세션이 실행된 터미널 앱을 사용합니다.", "hintPreferredTerminal")
        XCTAssertEqual(l10n.secAoEFocus, "AoE 세션 포커스", "secAoEFocus")
        XCTAssertEqual(l10n.lblAoEFocusMode, "포커스 방식", "lblAoEFocusMode")
        XCTAssertEqual(l10n.hintAoEFocusMode, "안전한 tmux 방식은 AoE에 /session 텍스트를 보내지 않습니다. 대시보드 행 이동이 필요할 때만 검색 방식을 사용하세요.", "hintAoEFocusMode")
        XCTAssertEqual(l10n.aoeFocusTmuxClient, "tmux 클라이언트 전환", "aoeFocusTmuxClient")
        XCTAssertEqual(l10n.aoeFocusManagerSearch, "AoE 대시보드 검색", "aoeFocusManagerSearch")
        XCTAssertEqual(l10n.detailAoEFocusTmuxClient, "터미널을 포커스하고 AoE에 입력하지 않은 채 tmux 클라이언트/패널을 전환합니다.", "detailAoEFocusTmuxClient")
        XCTAssertEqual(l10n.detailAoEFocusManagerSearch, "포커스 후 AoE 대시보드에 Ctrl+Q, /, 세션 이름, Enter를 보냅니다.", "detailAoEFocusManagerSearch")
        XCTAssertEqual(l10n.secStartup, "시작", "secStartup")
        XCTAssertEqual(l10n.lblLaunchAtLogin, "로그인 시 자동 시작", "lblLaunchAtLogin")
        XCTAssertEqual(l10n.lblLaunchAtLoginApproval, "시스템 설정에서 승인 필요", "lblLaunchAtLoginApproval")
        XCTAssertEqual(l10n.btnOpenLoginSettings, "로그인 항목 설정 열기…", "btnOpenLoginSettings")
        XCTAssertEqual(l10n.alertLaunchAtLoginFailed, "자동 시작 설정 변경 실패", "alertLaunchAtLoginFailed")
        XCTAssertEqual(l10n.secUpdates, "업데이트", "secUpdates")
        XCTAssertEqual(l10n.lblCheckForUpdatesOnStartup, "시작 시 업데이트 확인", "lblCheckForUpdatesOnStartup")
        XCTAssertEqual(l10n.lblReleaseChannel, "업데이트 채널", "lblReleaseChannel")
        XCTAssertEqual(l10n.releaseChannelStable, "안정 버전", "releaseChannelStable")
        XCTAssertEqual(l10n.releaseChannelNightly, "나이틀리", "releaseChannelNightly")
        XCTAssertEqual(l10n.secSounds, "사운드", "secSounds")
        XCTAssertEqual(l10n.lblMuteAllSounds, "모든 사운드 음소거", "lblMuteAllSounds")
        XCTAssertEqual(l10n.secNotifications, "알림", "secNotifications")
        XCTAssertEqual(l10n.lblNotificationsEnabled, "승인 요청 시 알림", "lblNotificationsEnabled")
        XCTAssertEqual(l10n.descNotificationsEnabled, "도구 승인이 필요할 때 macOS 알림을 보냅니다. 앱이 백그라운드에 있을 때 허용/거부 버튼이 표시됩니다.", "descNotificationsEnabled")
        XCTAssertEqual(l10n.notifActionApprove, "허용", "notifActionApprove")
        XCTAssertEqual(l10n.notifActionDeny, "거부", "notifActionDeny")
        XCTAssertEqual(l10n.notifApprovalBody, "승인이 필요합니다.", "notifApprovalBody")
        XCTAssertEqual(l10n.notifTaskCompleteTitle, "작업 완료", "notifTaskCompleteTitle")
        XCTAssertEqual(l10n.secNotch, "아일랜드", "secNotch")
        XCTAssertEqual(l10n.lblDisplay, "표시", "lblDisplay")
        XCTAssertEqual(l10n.lblMonitor, "모니터", "lblMonitor")
        XCTAssertEqual(l10n.lblShowFullScreen, "전체화면 앱 위에 표시", "lblShowFullScreen")
        XCTAssertEqual(l10n.lblPanelOpacity(7), "패널 불투명도: 7%", "lblPanelOpacity")
        XCTAssertEqual(l10n.lblNotchShadow, "백드롭 그림자", "lblNotchShadow")
        XCTAssertEqual(l10n.lblNotchAnimation, "펼침/접힘 애니메이션", "lblNotchAnimation")
        XCTAssertEqual(l10n.lblAnimationSpeed(1.25), "애니메이션 속도: 1.25×", "lblAnimationSpeed")
        XCTAssertEqual(l10n.lblNotchShapeStyle, "모양 스타일", "lblNotchShapeStyle")
        XCTAssertEqual(l10n.notchShapeClassic, "기본 아일랜드", "notchShapeClassic")
        XCTAssertEqual(l10n.notchShapeDynamicIsland, "다이나믹 아일랜드", "notchShapeDynamicIsland")
        XCTAssertEqual(l10n.lblCollapsedNotchWidth(7), "컴팩트 아일랜드 너비: 7 px", "lblCollapsedNotchWidth")
        XCTAssertEqual(l10n.lblCollapsedNotchHeight(7), "컴팩트 아일랜드 높이: 7 px", "lblCollapsedNotchHeight")
        XCTAssertEqual(l10n.lblExpandedNotchWidth(7), "확장 아일랜드 너비: 7 px", "lblExpandedNotchWidth")
        XCTAssertEqual(l10n.lblExpandedNotchHeight(7), "확장 아일랜드 높이: 7 px", "lblExpandedNotchHeight")
        XCTAssertEqual(l10n.lblNotchAutoExpand, "이벤트 시 자동 펼침", "lblNotchAutoExpand")
        XCTAssertEqual(l10n.lblUnreadDotPosition, "알림 dot 위치", "lblUnreadDotPosition")
        XCTAssertEqual(l10n.posLeft, "왼쪽", "posLeft")
        XCTAssertEqual(l10n.posCenter, "가운데", "posCenter")
        XCTAssertEqual(l10n.posRight, "오른쪽", "posRight")
        XCTAssertEqual(l10n.lblNotchAutoCollapse, "자동 닫힘", "lblNotchAutoCollapse")
        XCTAssertEqual(l10n.secNotchAutoExpand, "자동 펼침", "secNotchAutoExpand")
        XCTAssertEqual(l10n.secNotchExpandTriggers, "자동 펼침 조건", "secNotchExpandTriggers")
        XCTAssertEqual(l10n.lblExpandOnNotification, "알림 수신 시", "lblExpandOnNotification")
        XCTAssertEqual(l10n.lblExpandOnTaskCompletion, "작업 완료 시", "lblExpandOnTaskCompletion")
        XCTAssertEqual(l10n.lblExpandOnIdlePrompt, "대기 중 (입력 필요 시)", "lblExpandOnIdlePrompt")
        XCTAssertEqual(l10n.lblExpandOnNotificationMessage, "알림 메시지 수신 시", "lblExpandOnNotificationMessage")
        XCTAssertEqual(l10n.lblExpandOnInteractiveTool, "Gemini 인터랙티브 입력 시", "lblExpandOnInteractiveTool")
        XCTAssertEqual(l10n.lblExpandOnApprovalRequest, "승인 요청 시", "lblExpandOnApprovalRequest")
        XCTAssertEqual(l10n.lblExpandOnQuestionResponse, "질문 응답 대기 시", "lblExpandOnQuestionResponse")
        XCTAssertEqual(l10n.hintExpandOnNotification, "알림 이벤트 발생 시 펼칩니다. 하위 항목으로 종류를 선택하세요.", "hintExpandOnNotification")
        XCTAssertEqual(l10n.hintExpandOnTaskCompletion, "에이전트가 작업을 완료했을 때", "hintExpandOnTaskCompletion")
        XCTAssertEqual(l10n.hintExpandOnIdlePrompt, "에이전트가 완료 후 다음 프롬프트를 기다릴 때", "hintExpandOnIdlePrompt")
        XCTAssertEqual(l10n.hintExpandOnNotificationMessage, "에이전트가 질문이나 메시지를 알림으로 보낼 때", "hintExpandOnNotificationMessage")
        XCTAssertEqual(l10n.hintExpandOnInteractiveTool, "Gemini 전용 — 터미널 입력을 기다리는 인터랙티브 툴이 실행될 때", "hintExpandOnInteractiveTool")
        XCTAssertEqual(l10n.hintExpandOnApprovalRequest, "도구 사용 승인 요청이 수신될 때", "hintExpandOnApprovalRequest")
        XCTAssertEqual(l10n.hintExpandOnQuestionResponse, "에이전트가 사용자에게 질문을 보내고 응답을 기다릴 때", "hintExpandOnQuestionResponse")
        XCTAssertEqual(l10n.secNotchCharacters, "버디", "secNotchCharacters")
        XCTAssertEqual(l10n.lblLeftCharacter, "왼쪽 버디", "lblLeftCharacter")
        XCTAssertEqual(l10n.lblRightCharacter, "오른쪽 버디", "lblRightCharacter")
        XCTAssertEqual(l10n.lblCharacter, "버디", "lblCharacter")
        XCTAssertEqual(l10n.lblRandomIncludes, "랜덤 버디", "lblRandomIncludes")
        XCTAssertEqual(l10n.lblCharacterHorizontalInset(7), "버디 가로 위치: 7 px", "lblCharacterHorizontalInset")
        XCTAssertEqual(l10n.lblCharacterVerticalOffset(7), "버디 세로 위치: 7 px", "lblCharacterVerticalOffset")
        XCTAssertEqual(l10n.lblNotchCenterText, "가운데 텍스트", "lblNotchCenterText")
        XCTAssertEqual(l10n.secRequests, "요청", "secRequests")
        XCTAssertEqual(l10n.lblRequestDisplay, "요청 표시", "lblRequestDisplay")
        XCTAssertEqual(l10n.secAutoApprovals, "자동 승인", "secAutoApprovals")
        XCTAssertEqual(l10n.lblAutoSafe, "안전/읽기 전용 도구 자동 승인", "lblAutoSafe")
        XCTAssertEqual(l10n.lblGeminiEmulate, "위험 도구 승인 창 표시 (Gemini / Antigravity)", "lblGeminiEmulate")
        XCTAssertEqual(l10n.secPermissionTimeout, "권한 요청 타임아웃", "secPermissionTimeout")
        XCTAssertEqual(l10n.lblPermissionTimeout(7), "7초 후 자동 패스", "lblPermissionTimeout")
        XCTAssertEqual(l10n.secReplayRetention, "리플레이 로그 보관", "secReplayRetention")
        XCTAssertEqual(l10n.lblReplayRetention(7), "리플레이 로그: 7일", "lblReplayRetention")
        XCTAssertEqual(l10n.secFallback, "전송 실패 폴백", "secFallback")
        XCTAssertEqual(l10n.lblFallbackPolicy, "폴백 정책", "lblFallbackPolicy")
        XCTAssertEqual(l10n.lblSessionApproval, "세션 승인 방식", "lblSessionApproval")
        XCTAssertEqual(l10n.lblPersistentDest, "영구 승인 적용 범위", "lblPersistentDest")
        XCTAssertEqual(l10n.warnProjectSettings, "프로젝트 설정은 저장소에 커밋될 수 있습니다. 커밋 전에 변경 사항을 검토하세요.", "warnProjectSettings")
        XCTAssertEqual(l10n.descCodex, "Codex 세션 승인은 이후 단계에서 DevIsland 관리 캐시와 영구 SQLite 규칙을 사용합니다.", "descCodex")
        XCTAssertEqual(l10n.descGemini, "--auto-approve 또는 --yolo로 실행 중일 때도 위험한 도구는 승인을 요청합니다.", "descGemini")
        XCTAssertEqual(l10n.secTransport, "전송", "secTransport")
        XCTAssertEqual(l10n.lblTransport, "전송", "lblTransport")
        XCTAssertEqual(l10n.descTransport, "전송 변경 사항은 브리지 런타임 설정에 기록됩니다. 리스너 전송 방식 변경 후 DevIsland를 재시작하세요.", "descTransport")
        XCTAssertEqual(l10n.secTCP, "TCP", "secTCP")
        XCTAssertEqual(l10n.lblPort, "포트", "lblPort")
        XCTAssertEqual(l10n.secUnixSocket, "Unix 도메인 소켓", "secUnixSocket")
        XCTAssertEqual(l10n.lblSocketPath, "소켓 경로", "lblSocketPath")
        XCTAssertEqual(l10n.lblFallbackTCP, "TCP 루프백으로 폴백", "lblFallbackTCP")
        XCTAssertEqual(l10n.secTimeouts, "타임아웃", "secTimeouts")
        XCTAssertEqual(l10n.lblConnectTimeout, "연결 타임아웃", "lblConnectTimeout")
        XCTAssertEqual(l10n.lblResponseTimeout, "응답 타임아웃", "lblResponseTimeout")
        XCTAssertEqual(l10n.labelSeconds(7), "7초", "labelSeconds")
        XCTAssertEqual(l10n.secTokenSecurity, "토큰 보안", "secTokenSecurity")
        XCTAssertEqual(l10n.warnGraceMode, "IPC 토큰 파일이 없어 grace mode로 실행 중입니다. 모든 수신 연결이 인증 없이 허용됩니다.", "warnGraceMode")
        XCTAssertEqual(l10n.hintGraceModeResolve, "브리지를 재설치하면 토큰 파일이 생성됩니다.", "hintGraceModeResolve")
        XCTAssertEqual(l10n.secOpenPeonSoundPacks, "사운드팩", "secOpenPeonSoundPacks")
        XCTAssertEqual(l10n.lblOpenPeonEnable, "사운드 활성화", "lblOpenPeonEnable")
        XCTAssertEqual(l10n.phOpenPeonPacksFolder, "팩 폴더", "phOpenPeonPacksFolder")
        XCTAssertEqual(l10n.btnReload, "다시 불러오기", "btnReload")
        XCTAssertEqual(l10n.btnOpen, "열기", "btnOpen")
        XCTAssertEqual(l10n.btnPlayPreview, "미리듣기 재생", "btnPlayPreview")
        XCTAssertEqual(l10n.lblOpenPeonActivePack, "활성 팩", "lblOpenPeonActivePack")
        XCTAssertEqual(l10n.lblOpenPeonFirstValidPack, "첫 번째 유효한 팩", "lblOpenPeonFirstValidPack")
        XCTAssertEqual(l10n.lblOpenPeonNoPacks, "사운드팩을 찾을 수 없습니다.", "lblOpenPeonNoPacks")
        XCTAssertEqual(l10n.lblOpenPeonNoSoundFile, "이 이벤트에 대한 사운드 파일이 없습니다", "lblOpenPeonNoSoundFile")
        XCTAssertEqual(l10n.secOpenPeonPlayback, "재생", "secOpenPeonPlayback")
        XCTAssertEqual(l10n.lblOpenPeonMasterVolume, "마스터 볼륨", "lblOpenPeonMasterVolume")
        XCTAssertEqual(l10n.lblOpenPeonDebounce(7), "디바운스: 7ms", "lblOpenPeonDebounce")
        XCTAssertEqual(l10n.secOpenPeonCategories, "카테고리", "secOpenPeonCategories")
        XCTAssertEqual(l10n.secOpenPeonValidation, "검증", "secOpenPeonValidation")
        XCTAssertEqual(l10n.lblOpenPeonValid, "유효함", "lblOpenPeonValid")
        XCTAssertEqual(l10n.errOpenPeonReadPacks("path"), "path를 읽을 수 없습니다.", "errOpenPeonReadPacks")
        XCTAssertEqual(l10n.cespSessionStart, "세션 시작", "cespSessionStart")
        XCTAssertEqual(l10n.cespTaskAcknowledge, "작업 인지", "cespTaskAcknowledge")
        XCTAssertEqual(l10n.cespTaskComplete, "작업 완료", "cespTaskComplete")
        XCTAssertEqual(l10n.cespTaskError, "작업 오류", "cespTaskError")
        XCTAssertEqual(l10n.cespInputRequired, "입력 필요", "cespInputRequired")
        XCTAssertEqual(l10n.cespResourceLimit, "리소스 제한", "cespResourceLimit")
        XCTAssertEqual(l10n.cespUserSpam, "사용자 반복 입력", "cespUserSpam")
        XCTAssertEqual(l10n.cespSessionEnd, "세션 종료", "cespSessionEnd")
        XCTAssertEqual(l10n.cespTaskProgress, "작업 진행", "cespTaskProgress")
        XCTAssertEqual(l10n.secPTYWrapper, "PTY 래퍼", "secPTYWrapper")
        XCTAssertEqual(l10n.lblPTYEnable, "PTY 로깅 및 자동 주입 활성화", "lblPTYEnable")
        XCTAssertEqual(l10n.lblRetention(7), "트랜스크립트 보관: 7일", "lblRetention")
        XCTAssertEqual(l10n.btnViewPTY, "PTY 트랜스크립트 보기…", "btnViewPTY")
        XCTAssertEqual(l10n.secAutoInject, "자동 주입 패턴", "secAutoInject")
        XCTAssertEqual(l10n.lblNoPatterns, "패턴 없음. 아래에서 추가하세요.", "lblNoPatterns")
        XCTAssertEqual(l10n.phPattern, "패턴 (부분 문자열)", "phPattern")
        XCTAssertEqual(l10n.phResponse, "응답 텍스트", "phResponse")
        XCTAssertEqual(l10n.btnAdd, "추가", "btnAdd")
        XCTAssertEqual(l10n.secUsage, "사용법", "secUsage")
        XCTAssertEqual(l10n.descPTYUsage, "CLI 에이전트를 PTY 래퍼를 통해 실행:", "descPTYUsage")
        XCTAssertEqual(l10n.descPTYHooks, "스크립트가 PTYOutput 훅 이벤트를 앱으로 전달합니다.", "descPTYHooks")
        XCTAssertEqual(l10n.secCodexRules, "Codex 영구 SQLite 규칙", "secCodexRules")
        XCTAssertEqual(l10n.phToolName, "도구 이름", "phToolName")
        XCTAssertEqual(l10n.lblAction, "동작", "lblAction")
        XCTAssertEqual(l10n.lblAllow, "허용", "lblAllow")
        XCTAssertEqual(l10n.lblDeny, "거부", "lblDeny")
        XCTAssertEqual(l10n.btnExportSnapshot, "스냅샷 내보내기", "btnExportSnapshot")
        XCTAssertEqual(l10n.lblNoCodexRules, "구성된 Codex 영구 SQLite 규칙이 없습니다.", "lblNoCodexRules")
        XCTAssertEqual(l10n.secGlobalRules, "전역 자동 승인 도구", "secGlobalRules")
        XCTAssertEqual(l10n.descGlobalRules, "이 DevIsland 규칙은 승인 프롬프트 표시 전 모든 세션에서 확인됩니다.", "descGlobalRules")
        XCTAssertEqual(l10n.alertAddGlobalToolTitle, "글로벌 자동 승인 툴 추가", "alertAddGlobalToolTitle")
        XCTAssertEqual(l10n.alertAddGlobalToolMsg, "모든 세션에서 자동 승인할 툴 이름(예: read_file)을 입력하세요.", "alertAddGlobalToolMsg")
        XCTAssertEqual(l10n.alertAddSessionToolTitle, "세션 자동 승인 툴 추가", "alertAddSessionToolTitle")
        XCTAssertEqual(l10n.alertAddSessionToolMsg("id"), "현재 세션(id)에서 자동 승인할 툴 이름을 입력하세요.", "alertAddSessionToolMsg")
        XCTAssertEqual(l10n.btnAddManually, "직접 추가…", "btnAddManually")
        XCTAssertEqual(l10n.btnAddFromList, "목록에서 추가", "btnAddFromList")
        XCTAssertEqual(l10n.lblNoGlobalTools, "구성된 전역 자동 승인 도구가 없습니다.", "lblNoGlobalTools")
        XCTAssertEqual(l10n.btnRemoveAllGlobal, "전역 도구 모두 제거", "btnRemoveAllGlobal")
        XCTAssertEqual(l10n.secSessionRules, "세션 자동 승인 도구", "secSessionRules")
        XCTAssertEqual(l10n.descSessionRules, "세션 규칙은 해당 활성 세션이 제거될 때까지 유지됩니다.", "descSessionRules")
        XCTAssertEqual(l10n.lblNoSessions, "활성 세션 없음.", "lblNoSessions")
        XCTAssertEqual(l10n.lblNoSessionTools, "구성된 세션 자동 승인 도구가 없습니다.", "lblNoSessionTools")
        XCTAssertEqual(l10n.btnRemoveAllSession, "세션 도구 모두 제거", "btnRemoveAllSession")
        XCTAssertEqual(l10n.lblSession("id", 7), "세션 id (7개 도구)", "lblSession")
        XCTAssertEqual(l10n.errSaveCodexRule("err"), "Codex 규칙 저장 실패: err", "errSaveCodexRule")
        XCTAssertEqual(l10n.errDeleteCodexRule("err"), "Codex 규칙 삭제 실패: err", "errDeleteCodexRule")
        XCTAssertEqual(l10n.errLoadCodexRules("err"), "Codex 규칙 로드 실패: err", "errLoadCodexRules")
        XCTAssertEqual(l10n.exportedCodexRules(7, "path"), "path에 Codex 규칙 7개 내보냄", "exportedCodexRules")
        XCTAssertEqual(l10n.errExportCodexRules("err"), "Codex 규칙 내보내기 실패: err", "errExportCodexRules")
        XCTAssertEqual(l10n.addAllRisk("name"), "name 도구 모두 추가", "addAllRisk")
        XCTAssertEqual(l10n.monitorMain(), "주 모니터", "monitorMain")
        XCTAssertEqual(l10n.monitorN(7), "모니터 7", "monitorN")
        XCTAssertEqual(l10n.notchAuto, "자동", "notchAuto")
        XCTAssertEqual(l10n.notchMain, "주 모니터", "notchMain")
        XCTAssertEqual(l10n.notchMouse, "마우스가 있는 모니터", "notchMouse")
        XCTAssertEqual(l10n.notchFocused, "포커스가 있는 모니터", "notchFocused")
        XCTAssertEqual(l10n.notchSpecific, "선택한 모니터", "notchSpecific")
        XCTAssertEqual(l10n.notchCharacterHidden, "숨김", "notchCharacterHidden")
        XCTAssertEqual(l10n.notchCharacterRandom, "랜덤", "notchCharacterRandom")
        XCTAssertEqual(l10n.notchCharacterSpecific, "지정", "notchCharacterSpecific")
        XCTAssertEqual(l10n.notchAutoCollapseOff, "끔", "notchAutoCollapseOff")
        XCTAssertEqual(l10n.reqNotch, "아일랜드 화면", "reqNotch")
        XCTAssertEqual(l10n.reqFocused, "포커스 화면", "reqFocused")
        XCTAssertEqual(l10n.reqMouse, "마우스 화면", "reqMouse")
        XCTAssertEqual(l10n.modeNative, "Claude 기본 권한", "modeNative")
        XCTAssertEqual(l10n.modeCache, "DevIsland 관리 세션 캐시", "modeCache")
        XCTAssertEqual(l10n.modeHybrid, "하이브리드", "modeHybrid")
        XCTAssertEqual(l10n.detailNative, "권장. 승인 내역을 Claude가 관리합니다. 가장 안정적입니다.", "detailNative")
        XCTAssertEqual(l10n.detailCache, "DevIsland가 세션 중 승인한 도구를 기억해 다시 묻지 않습니다.", "detailCache")
        XCTAssertEqual(l10n.detailHybrid, "Claude 방식을 우선 사용하고, 지원되지 않으면 DevIsland가 처리합니다.", "detailHybrid")
        XCTAssertEqual(l10n.destLocal, "프로젝트 로컬", "destLocal")
        XCTAssertEqual(l10n.destProject, "프로젝트 공유", "destProject")
        XCTAssertEqual(l10n.destUser, "사용자 전체", "destUser")
        XCTAssertEqual(l10n.detailDestLocal, "이 프로젝트에만 적용됩니다. git에 커밋되지 않습니다. (.claude/settings.local.json)", "detailDestLocal")
        XCTAssertEqual(l10n.detailDestProject, "팀원과 공유됩니다. git에 커밋될 수 있습니다. (.claude/settings.json)", "detailDestProject")
        XCTAssertEqual(l10n.detailDestUser, "모든 프로젝트에 적용됩니다. (~/.claude/settings.json)", "detailDestUser")
        XCTAssertEqual(l10n.transportTCP, "TCP 루프백", "transportTCP")
        XCTAssertEqual(l10n.transportUnix, "Unix 도메인 소켓", "transportUnix")
        XCTAssertEqual(l10n.fallbackPass, "통과 (CLI에 위임)", "fallbackPass")
        XCTAssertEqual(l10n.fallbackDeny, "거부", "fallbackDeny")
        XCTAssertEqual(l10n.fleetTitle, "Fleet Radar", "fleetTitle")
        XCTAssertEqual(l10n.fleetEmptyState, "지원되는 에이전트 세션을 시작하면 여기에 표시됩니다.", "fleetEmptyState")
        XCTAssertEqual(l10n.fleetRefreshing, "Fleet Radar 새로 고치는 중", "fleetRefreshing")
        XCTAssertEqual(l10n.fleetActiveCardsCount(1), "활성 카드 1개", "fleetActiveCardsCount(singular)")
        XCTAssertEqual(l10n.fleetActiveCardsCount(7), "활성 카드 7개", "fleetActiveCardsCount")
        XCTAssertEqual(l10n.fleetWorktreesCount(1), "작업 트리 1개", "fleetWorktreesCount(singular)")
        XCTAssertEqual(l10n.fleetWorktreesCount(7), "작업 트리 7개", "fleetWorktreesCount")
        XCTAssertEqual(l10n.fleetOverlapPairsCount(1), "겹침 쌍 1개", "fleetOverlapPairsCount(singular)")
        XCTAssertEqual(l10n.fleetOverlapPairsCount(7), "겹침 쌍 7개", "fleetOverlapPairsCount")
        XCTAssertEqual(l10n.fleetUpdated, "업데이트", "fleetUpdated")
        XCTAssertEqual(l10n.fleetRefresh, "새로 고침", "fleetRefresh")
        XCTAssertEqual(l10n.fleetRefreshHelp, "캐시를 무시하고 모든 Git 컨텍스트 새로 고침", "fleetRefreshHelp")
        XCTAssertEqual(l10n.fleetAttentionNeedsDecision, "결정 필요", "fleetAttentionNeedsDecision")
        XCTAssertEqual(l10n.fleetAttentionBlocked, "차단됨", "fleetAttentionBlocked")
        XCTAssertEqual(l10n.fleetAttentionOverlapRisk, "겹침 위험", "fleetAttentionOverlapRisk")
        XCTAssertEqual(l10n.fleetAttentionUnread, "읽지 않음", "fleetAttentionUnread")
        XCTAssertEqual(l10n.fleetAttentionLive, "진행 중", "fleetAttentionLive")
        XCTAssertEqual(l10n.fleetAttention(.needsDecision), "결정 필요", "fleetAttention(needsDecision)")
        XCTAssertEqual(l10n.fleetAttention(.blocked), "차단됨", "fleetAttention(blocked)")
        XCTAssertEqual(l10n.fleetAttention(.overlapRisk), "겹침 위험", "fleetAttention(overlapRisk)")
        XCTAssertEqual(l10n.fleetAttention(.unread), "읽지 않음", "fleetAttention(unread)")
        XCTAssertEqual(l10n.fleetAttention(.live), "진행 중", "fleetAttention(live)")
        XCTAssertEqual(l10n.fleetClean, "변경 없음", "fleetClean")
        XCTAssertEqual(l10n.fleetDirtyCount(1), "변경 있음 · 파일 1개", "fleetDirtyCount(singular)")
        XCTAssertEqual(l10n.fleetDirtyCount(7), "변경 있음 · 파일 7개", "fleetDirtyCount")
        XCTAssertEqual(l10n.fleetUnmerged, "병합되지 않음", "fleetUnmerged")
        XCTAssertEqual(l10n.fleetStale, "이전 결과", "fleetStale")
        XCTAssertEqual(l10n.fleetUnavailable, "사용할 수 없음", "fleetUnavailable")
        XCTAssertEqual(l10n.fleetWorkspaceUnavailable, "작업 공간을 사용할 수 없음", "fleetWorkspaceUnavailable")
        XCTAssertEqual(l10n.fleetNotRepository, "Git 저장소가 아님", "fleetNotRepository")
        XCTAssertEqual(l10n.fleetGitContextUnavailable, "Git 컨텍스트를 사용할 수 없음", "fleetGitContextUnavailable")
        XCTAssertEqual(l10n.fleetRetry, "다시 시도", "fleetRetry")
        XCTAssertEqual(l10n.fleetOverlapRisk, "겹침 위험", "fleetOverlapRisk")
        XCTAssertEqual(l10n.fleetOverlapCount(1), "겹침 1개", "fleetOverlapCount(singular)")
        XCTAssertEqual(l10n.fleetOverlapCount(7), "겹침 7개", "fleetOverlapCount")
        XCTAssertEqual(l10n.fleetFilesCount(1), "파일 1개", "fleetFilesCount(singular)")
        XCTAssertEqual(l10n.fleetFilesCount(7), "파일 7개", "fleetFilesCount")
        XCTAssertEqual(l10n.fleetOverlapDetails, "겹침 상세", "fleetOverlapDetails")
        XCTAssertEqual(l10n.fleetOverlapDetailsHelp, "작업 트리별 겹친 경로 보기", "fleetOverlapDetailsHelp")
        XCTAssertEqual(l10n.fleetMoreOverlaps(1), "겹침 1개 더 있음", "fleetMoreOverlaps(singular)")
        XCTAssertEqual(l10n.fleetMoreOverlaps(7), "겹침 7개 더 있음", "fleetMoreOverlaps")
        XCTAssertEqual(l10n.fleetMoreFiles(1), "파일 1개 더 있음", "fleetMoreFiles(singular)")
        XCTAssertEqual(l10n.fleetMoreFiles(7), "파일 7개 더 있음", "fleetMoreFiles")
        XCTAssertEqual(l10n.fleetOverlapDisclaimer, "이는 경로 겹침이며 반드시 병합 충돌이 발생한다는 의미는 아닙니다.", "fleetOverlapDisclaimer")
        XCTAssertEqual(l10n.fleetRecentActivity, "최근 활동", "fleetRecentActivity")
        XCTAssertEqual(l10n.fleetNoRecentActivity, "최근 활동 없음", "fleetNoRecentActivity")
        XCTAssertEqual(l10n.fleetSubagents, "하위 에이전트", "fleetSubagents")
        XCTAssertEqual(l10n.fleetOrphanSubagent, "독립 하위 에이전트", "fleetOrphanSubagent")
        XCTAssertEqual(l10n.fleetMoreSubagents(1), "1개 더 보기", "fleetMoreSubagents(singular)")
        XCTAssertEqual(l10n.fleetMoreSubagents(7), "7개 더 보기", "fleetMoreSubagents")
        XCTAssertEqual(l10n.fleetShowFewer, "접기", "fleetShowFewer")
        XCTAssertEqual(l10n.fleetShowDetail, "상세 보기", "fleetShowDetail")
        XCTAssertEqual(l10n.fleetShowDetailHelp, "터미널 포커스 없이 아일랜드에서 이 세션 보기", "fleetShowDetailHelp")
        XCTAssertEqual(l10n.fleetFocusTerminal, "터미널 포커스", "fleetFocusTerminal")
        XCTAssertEqual(l10n.fleetFocusTerminalHelp, "터미널에 포커스합니다. 표시 중인 승인 요청이 터미널로 돌아갈 수 있습니다.", "fleetFocusTerminalHelp")
        XCTAssertEqual(l10n.fleetOpenInFinder, "Finder에서 열기", "fleetOpenInFinder")
        XCTAssertEqual(l10n.fleetOpenInFinderHelp, "Finder에서 작업 공간 열기", "fleetOpenInFinderHelp")
        XCTAssertEqual(l10n.fleetCopyPath, "경로 복사", "fleetCopyPath")
        XCTAssertEqual(l10n.fleetCopyPathHelp, "작업 공간 경로 복사", "fleetCopyPathHelp")
        XCTAssertEqual(
            l10n.fleetCardAccessibility("title", "provider", "attention", "branch", "dirty", "overlap"),
            "title, provider, attention, 브랜치 branch, dirty, overlap",
            "fleetCardAccessibility"
        )
        XCTAssertEqual(l10n.popOutWindow, "메시지 창 분리", "popOutWindow")
        XCTAssertEqual(l10n.sessionEnded, "세션이 종료되었습니다", "sessionEnded")
        XCTAssertEqual(l10n.msgWaiting, "메시지 대기 중…", "msgWaiting")
        XCTAssertEqual(l10n.approvingOtherSession, "다른 세션 승인 처리 중…", "approvingOtherSession")
        XCTAssertEqual(l10n.notchApprovalRequired, "승인 필요", "notchApprovalRequired")
        XCTAssertEqual(l10n.notchNotification, "알림", "notchNotification")
        XCTAssertEqual(l10n.notchMonitoring, "모니터링", "notchMonitoring")
        XCTAssertEqual(l10n.notchActiveAction, "활성 작업", "notchActiveAction")
        XCTAssertEqual(l10n.notchAgentSessions, "에이전트 세션", "notchAgentSessions")
        XCTAssertEqual(l10n.notchListening, "AI 에이전트 대기 중…", "notchListening")
        XCTAssertEqual(l10n.terminalWaiting, "터미널 확인 대기 중...", "terminalWaiting")
        XCTAssertEqual(l10n.terminalCheckMsg("tool"), "터미널 창을 확인해 주세요 (tool)", "terminalCheckMsg")
        XCTAssertEqual(l10n.notchSessions, "세션", "notchSessions")
        XCTAssertEqual(l10n.notchFocus, "포커스", "notchFocus")
        XCTAssertEqual(l10n.notchDenyRequest, "요청 거부", "notchDenyRequest")
        XCTAssertEqual(l10n.notchApprove, "승인", "notchApprove")
        XCTAssertEqual(l10n.notchAutoApproveSession, "이 세션에서 자동 승인", "notchAutoApproveSession")
        XCTAssertEqual(l10n.notchAlwaysAutoApprove, "항상 자동 승인 (전역)", "notchAlwaysAutoApprove")
        XCTAssertEqual(l10n.notchAlwaysAllowSuggestion, "이 도구를 항상 허용할까요?", "notchAlwaysAllowSuggestion")
        XCTAssertEqual(l10n.notchAlwaysAllowSuggestionHelp("tool"), "'tool'을(를) 여러 번 승인했습니다. 클릭하면 영구 허용 규칙이 추가됩니다.", "notchAlwaysAllowSuggestionHelp")
        XCTAssertEqual(l10n.notchFocusTerminal, "터미널 포커스", "notchFocusTerminal")
        XCTAssertEqual(l10n.notchDismiss, "닫기", "notchDismiss")
        XCTAssertEqual(l10n.notchUnknown, "알 수 없음", "notchUnknown")
        XCTAssertEqual(l10n.helpOpenSettings, "설정 열기", "helpOpenSettings")
        XCTAssertEqual(l10n.helpFocusTerminal, "터미널 포커스", "helpFocusTerminal")
        XCTAssertEqual(l10n.helpDismissSession, "세션 닫기", "helpDismissSession")
        XCTAssertEqual(l10n.menuOpenInFinder, "Finder에서 열기", "menuOpenInFinder")
        XCTAssertEqual(l10n.menuCopyPath, "경로 복사", "menuCopyPath")
        XCTAssertEqual(l10n.menuCopyResumeCommand, "재시작 명령 복사", "menuCopyResumeCommand")
        XCTAssertEqual(l10n.menuRenameSession, "이름 변경…", "menuRenameSession")
        XCTAssertEqual(l10n.menuEditSessionDescription, "설명 편집…", "menuEditSessionDescription")
        XCTAssertEqual(l10n.menuAddFavorite, "즐겨찾기에 추가", "menuAddFavorite")
        XCTAssertEqual(l10n.menuRemoveFavorite, "즐겨찾기에서 제거", "menuRemoveFavorite")
        XCTAssertEqual(l10n.renameSessionTitle, "세션 이름 변경", "renameSessionTitle")
        XCTAssertEqual(l10n.renameSessionConfirm, "변경", "renameSessionConfirm")
        XCTAssertEqual(l10n.renameSessionPlaceholder, "세션 이름", "renameSessionPlaceholder")
        XCTAssertEqual(l10n.sessionDescriptionTitle, "세션 설명", "sessionDescriptionTitle")
        XCTAssertEqual(l10n.sessionDescriptionConfirm, "저장", "sessionDescriptionConfirm")
        XCTAssertEqual(l10n.btnCancel, "취소", "btnCancel")
        XCTAssertEqual(l10n.renameSessionHint("id"), "세션 id의 이름을 입력하세요. 비워두면 초기화됩니다.", "renameSessionHint")
        XCTAssertEqual(l10n.sessionDescriptionHint("id"), "세션 id의 설명을 입력하세요. 비워두면 삭제됩니다.", "sessionDescriptionHint")
        XCTAssertEqual(l10n.menuOpenInTerminal, "터미널에서 열기", "menuOpenInTerminal")
        XCTAssertEqual(l10n.menuTerminalAuto("name"), "자동 (name)", "menuTerminalAuto")
        XCTAssertEqual(l10n.menuStartNewSession, "이 위치에서 새 세션", "menuStartNewSession")
        XCTAssertEqual(l10n.helpDismissPending, "세션을 닫고 대기 중인 요청을 터미널로 전달", "helpDismissPending")
        XCTAssertEqual(l10n.tasksQueued(7), "7개 대기 중", "tasksQueued")
        XCTAssertEqual(l10n.timeJustNow(), "방금", "timeJustNow")
        XCTAssertEqual(l10n.timeSecsAgo(7), "7초 전", "timeSecsAgo")
        XCTAssertEqual(l10n.timeMinsAgo(7), "7분 전", "timeMinsAgo")
        XCTAssertEqual(l10n.historyTabSessions, "세션", "historyTabSessions")
        XCTAssertEqual(l10n.historyTabInsights, "인사이트", "historyTabInsights")
        XCTAssertEqual(l10n.insightsTodaySessions, "오늘", "insightsTodaySessions")
        XCTAssertEqual(l10n.insightsTotalSessions, "전체 (보존 기간)", "insightsTotalSessions")
        XCTAssertEqual(l10n.insightsAvgDuration, "평균 소요 시간", "insightsAvgDuration")
        XCTAssertEqual(l10n.insightsApprovals, "승인 현황", "insightsApprovals")
        XCTAssertEqual(l10n.insightsManualApproved, "수동 승인", "insightsManualApproved")
        XCTAssertEqual(l10n.insightsManualDenied, "수동 거부", "insightsManualDenied")
        XCTAssertEqual(l10n.insightsAutoApproved, "자동 승인", "insightsAutoApproved")
        XCTAssertEqual(l10n.insightsAutoDenied, "정책 거부", "insightsAutoDenied")
        XCTAssertEqual(l10n.insightsTopTools, "자주 승인된 도구", "insightsTopTools")
        XCTAssertEqual(l10n.insightsNoData, "데이터 없음", "insightsNoData")
        XCTAssertEqual(l10n.insightsRetentionNote, "리플레이 로그 보존 기간 기준", "insightsRetentionNote")
        XCTAssertEqual(l10n.insightsDuration("s"), "평균 s", "insightsDuration")
        XCTAssertEqual(l10n.historySearch, "세션 검색…", "historySearch")
        XCTAssertEqual(l10n.historyEmpty, "세션 없음", "historyEmpty")
        XCTAssertEqual(l10n.historyFilterAll, "전체", "historyFilterAll")
        XCTAssertEqual(l10n.historyFilterFavorites, "즐겨찾기", "historyFilterFavorites")
        XCTAssertEqual(l10n.historyRefresh, "새로 고침", "historyRefresh")
        XCTAssertEqual(l10n.historyColFavorite, "즐겨찾기", "historyColFavorite")
        XCTAssertEqual(l10n.historyColStatus, "상태", "historyColStatus")
        XCTAssertEqual(l10n.historyColAgent, "에이전트", "historyColAgent")
        XCTAssertEqual(l10n.historyColPath, "경로", "historyColPath")
        XCTAssertEqual(l10n.historyColLabel, "이름", "historyColLabel")
        XCTAssertEqual(l10n.historyColDescription, "설명", "historyColDescription")
        XCTAssertEqual(l10n.historyColTitle, "터미널", "historyColTitle")
        XCTAssertEqual(l10n.historyColEnded, "종료", "historyColEnded")
        XCTAssertEqual(l10n.historyColSession, "세션 ID", "historyColSession")
        XCTAssertEqual(l10n.historyStatusLive, "진행 중", "historyStatusLive")
        XCTAssertEqual(l10n.historyStatusEnded, "종료됨", "historyStatusEnded")
        XCTAssertEqual(l10n.historyCount(7), "7개 세션", "historyCount")
        XCTAssertEqual(l10n.statusPending, "대기 중", "statusPending")
        XCTAssertEqual(l10n.statusBypassed, "우회됨", "statusBypassed")
        XCTAssertEqual(l10n.statusAutoApproved, "자동 승인됨", "statusAutoApproved")
        XCTAssertEqual(l10n.statusPolicyApproved, "정책 승인됨", "statusPolicyApproved")
        XCTAssertEqual(l10n.statusPolicyDenied, "정책 거부됨", "statusPolicyDenied")
        XCTAssertEqual(l10n.statusAutoEdit, "자동 편집", "statusAutoEdit")
        XCTAssertEqual(l10n.notifTaskCompleteBody(""), "에이전트가 작업을 완료했습니다.", "notifTaskCompleteBody(empty)")
        XCTAssertEqual(l10n.notifTaskCompleteBody("Build"), "Build 완료", "notifTaskCompleteBody(nonempty)")
    }
}
